/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.evidenciesib.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ConstantsWs
 */


public class ConstantsWs {
  @JsonProperty("EVIDENCIA_ESTAT_CODI_ERROR")
  private Integer EVIDENCIA_ESTAT_CODI_ERROR = -1;

  @JsonProperty("EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO")
  private Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO = 1;

  @JsonProperty("EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN")
  private Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN = 2;

  @JsonProperty("EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA")
  private Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA = 3;

  @JsonProperty("EVIDENCIA_ESTAT_CODI_SIGNAT")
  private Integer EVIDENCIA_ESTAT_CODI_SIGNAT = 10;

   /**
   * Codi d&#x27;estat d&#x27;una evidència que indica un error
   * @return EVIDENCIA_ESTAT_CODI_ERROR
  **/
  @Schema(required = true, description = "Codi d'estat d'una evidència que indica un error")
  public Integer getEVIDENCIAESTATCODIERROR() {
    return EVIDENCIA_ESTAT_CODI_ERROR;
  }

   /**
   * Codi d&#x27;estat d&#x27;una evidència que indica que esta en procés de creació
   * @return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO
  **/
  @Schema(required = true, description = "Codi d'estat d'una evidència que indica que esta en procés de creació")
  public Integer getEVIDENCIAESTATCODIENPROCESDECREACIO() {
    return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO;
  }

   /**
   * Codi d&#x27;estat d&#x27;una evidència que indica que esta realitzant el login
   * @return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN
  **/
  @Schema(required = true, description = "Codi d'estat d'una evidència que indica que esta realitzant el login")
  public Integer getEVIDENCIAESTATCODIENPROCESDELOGIN() {
    return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN;
  }

   /**
   * Codi d&#x27;estat d&#x27;una evidència que indica que esta realitzant la firma del document
   * @return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA
  **/
  @Schema(required = true, description = "Codi d'estat d'una evidència que indica que esta realitzant la firma del document")
  public Integer getEVIDENCIAESTATCODIENPROCESDEFIRMA() {
    return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA;
  }

   /**
   * Codi d&#x27;estat d&#x27;una evidència que indica que ha finalitzat correctament
   * @return EVIDENCIA_ESTAT_CODI_SIGNAT
  **/
  @Schema(required = true, description = "Codi d'estat d'una evidència que indica que ha finalitzat correctament")
  public Integer getEVIDENCIAESTATCODISIGNAT() {
    return EVIDENCIA_ESTAT_CODI_SIGNAT;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConstantsWs constantsWs = (ConstantsWs) o;
    return Objects.equals(this.EVIDENCIA_ESTAT_CODI_ERROR, constantsWs.EVIDENCIA_ESTAT_CODI_ERROR) &&
        Objects.equals(this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO, constantsWs.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO) &&
        Objects.equals(this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN, constantsWs.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN) &&
        Objects.equals(this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA, constantsWs.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA) &&
        Objects.equals(this.EVIDENCIA_ESTAT_CODI_SIGNAT, constantsWs.EVIDENCIA_ESTAT_CODI_SIGNAT);
  }

  @Override
  public int hashCode() {
    return Objects.hash(EVIDENCIA_ESTAT_CODI_ERROR, EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO, EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN, EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA, EVIDENCIA_ESTAT_CODI_SIGNAT);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConstantsWs {\n");
    
    sb.append("    EVIDENCIA_ESTAT_CODI_ERROR: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_ERROR)).append("\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO)).append("\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN)).append("\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA)).append("\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_SIGNAT: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_SIGNAT)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
