/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConstantsWs
 */
@JsonPropertyOrder({
  ConstantsWs.JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_R_R_O_R,
  ConstantsWs.JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_C_R_E_A_C_I_O,
  ConstantsWs.JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_L_O_G_I_N,
  ConstantsWs.JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_F_I_R_M_A,
  ConstantsWs.JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_S_I_G_N_A_T
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ConstantsWs {
  public static final String JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_R_R_O_R = "EVIDENCIA_ESTAT_CODI_ERROR";
  private Integer EVIDENCIA_ESTAT_CODI_ERROR = -1;

  public static final String JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_C_R_E_A_C_I_O = "EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO";
  private Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO = 1;

  public static final String JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_L_O_G_I_N = "EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN";
  private Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN = 2;

  public static final String JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_F_I_R_M_A = "EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA";
  private Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA = 3;

  public static final String JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_S_I_G_N_A_T = "EVIDENCIA_ESTAT_CODI_SIGNAT";
  private Integer EVIDENCIA_ESTAT_CODI_SIGNAT = 10;

  public ConstantsWs() {
  }

  @JsonCreator
  public ConstantsWs(
    @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_R_R_O_R) Integer EVIDENCIA_ESTAT_CODI_ERROR, 
    @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_C_R_E_A_C_I_O) Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO, 
    @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_L_O_G_I_N) Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN, 
    @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_F_I_R_M_A) Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA, 
    @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_S_I_G_N_A_T) Integer EVIDENCIA_ESTAT_CODI_SIGNAT
  ) {
    this();
    this.EVIDENCIA_ESTAT_CODI_ERROR = EVIDENCIA_ESTAT_CODI_ERROR;
    this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO = EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO;
    this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN = EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN;
    this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA = EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA;
    this.EVIDENCIA_ESTAT_CODI_SIGNAT = EVIDENCIA_ESTAT_CODI_SIGNAT;
  }

   /**
   * Codi d&#39;estat d&#39;una evidència que indica un error
   * @return EVIDENCIA_ESTAT_CODI_ERROR
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_R_R_O_R)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEVIDENCIAESTATCODIERROR() {
    return EVIDENCIA_ESTAT_CODI_ERROR;
  }




   /**
   * Codi d&#39;estat d&#39;una evidència que indica que esta en procés de creació
   * @return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_C_R_E_A_C_I_O)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEVIDENCIAESTATCODIENPROCESDECREACIO() {
    return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO;
  }




   /**
   * Codi d&#39;estat d&#39;una evidència que indica que esta realitzant el login
   * @return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_L_O_G_I_N)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEVIDENCIAESTATCODIENPROCESDELOGIN() {
    return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN;
  }




   /**
   * Codi d&#39;estat d&#39;una evidència que indica que esta realitzant la firma del document
   * @return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_F_I_R_M_A)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEVIDENCIAESTATCODIENPROCESDEFIRMA() {
    return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA;
  }




   /**
   * Codi d&#39;estat d&#39;una evidència que indica que ha finalitzat correctament
   * @return EVIDENCIA_ESTAT_CODI_SIGNAT
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_S_I_G_N_A_T)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEVIDENCIAESTATCODISIGNAT() {
    return EVIDENCIA_ESTAT_CODI_SIGNAT;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConstantsWs constantsWs = (ConstantsWs) o;
    return Objects.equals(this.EVIDENCIA_ESTAT_CODI_ERROR, constantsWs.EVIDENCIA_ESTAT_CODI_ERROR) &&
        Objects.equals(this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO, constantsWs.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO) &&
        Objects.equals(this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN, constantsWs.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN) &&
        Objects.equals(this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA, constantsWs.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA) &&
        Objects.equals(this.EVIDENCIA_ESTAT_CODI_SIGNAT, constantsWs.EVIDENCIA_ESTAT_CODI_SIGNAT);
  }

  @Override
  public int hashCode() {
    return Objects.hash(EVIDENCIA_ESTAT_CODI_ERROR, EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO, EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN, EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA, EVIDENCIA_ESTAT_CODI_SIGNAT);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConstantsWs {\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_ERROR: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_ERROR)).append("\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO)).append("\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN)).append("\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA)).append("\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_SIGNAT: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_SIGNAT)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

