/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.evidenciesib.apiexterna.client.model.EvidenciaFile;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Estructura que inclou tota la informació de l&#39;evidència.
 */
@JsonPropertyOrder({
  EvidenciaWs.JSON_PROPERTY_EVIDENCIA_I_D,
  EvidenciaWs.JSON_PROPERTY_NOM,
  EvidenciaWs.JSON_PROPERTY_PERSONA_NOM,
  EvidenciaWs.JSON_PROPERTY_PERSONA_LLINATGE1,
  EvidenciaWs.JSON_PROPERTY_PERSONA_LLINATGE2,
  EvidenciaWs.JSON_PROPERTY_PERSONA_NIF,
  EvidenciaWs.JSON_PROPERTY_PERSONA_EMAIL,
  EvidenciaWs.JSON_PROPERTY_PERSONA_MOBIL,
  EvidenciaWs.JSON_PROPERTY_DATA_INICI,
  EvidenciaWs.JSON_PROPERTY_DATA_FI,
  EvidenciaWs.JSON_PROPERTY_ESTAT_CODI,
  EvidenciaWs.JSON_PROPERTY_ESTAT_CODI_DESCRIPCIO,
  EvidenciaWs.JSON_PROPERTY_ESTAT_ERROR,
  EvidenciaWs.JSON_PROPERTY_ESTAT_EXCEPCIO,
  EvidenciaWs.JSON_PROPERTY_LOGIN_TYPE,
  EvidenciaWs.JSON_PROPERTY_LOGIN_SUBTYPE,
  EvidenciaWs.JSON_PROPERTY_LOGIN_QAA,
  EvidenciaWs.JSON_PROPERTY_LOGIN_DATA,
  EvidenciaWs.JSON_PROPERTY_LOGIN_ID,
  EvidenciaWs.JSON_PROPERTY_LOGIN_AUTH_METHOD,
  EvidenciaWs.JSON_PROPERTY_LOGIN_ADDITIONAL_PROPERTIES,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_IP,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_CODI_POSTAL,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_LATITUD,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_LONGITUD,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_CIUTAT,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_REGIO,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_PAIS,
  EvidenciaWs.JSON_PROPERTY_FIRMA_REASON,
  EvidenciaWs.JSON_PROPERTY_FIRMA_IDIOMA_DOCUMENT,
  EvidenciaWs.JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL,
  EvidenciaWs.JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL_DESCRIPCIO,
  EvidenciaWs.JSON_PROPERTY_FITXER_ORIGINAL,
  EvidenciaWs.JSON_PROPERTY_FITXER_ADAPTAT,
  EvidenciaWs.JSON_PROPERTY_FITXER_SIGNAT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EvidenciaWs {
  public static final String JSON_PROPERTY_EVIDENCIA_I_D = "evidenciaID";
  private Long evidenciaID;

  public static final String JSON_PROPERTY_NOM = "nom";
  private String nom;

  public static final String JSON_PROPERTY_PERSONA_NOM = "personaNom";
  private String personaNom;

  public static final String JSON_PROPERTY_PERSONA_LLINATGE1 = "personaLlinatge1";
  private String personaLlinatge1;

  public static final String JSON_PROPERTY_PERSONA_LLINATGE2 = "personaLlinatge2";
  private String personaLlinatge2;

  public static final String JSON_PROPERTY_PERSONA_NIF = "personaNif";
  private String personaNif;

  public static final String JSON_PROPERTY_PERSONA_EMAIL = "personaEmail";
  private String personaEmail;

  public static final String JSON_PROPERTY_PERSONA_MOBIL = "personaMobil";
  private String personaMobil;

  public static final String JSON_PROPERTY_DATA_INICI = "dataInici";
  private OffsetDateTime dataInici;

  public static final String JSON_PROPERTY_DATA_FI = "dataFi";
  private OffsetDateTime dataFi;

  public static final String JSON_PROPERTY_ESTAT_CODI = "estatCodi";
  private Integer estatCodi;

  public static final String JSON_PROPERTY_ESTAT_CODI_DESCRIPCIO = "estatCodiDescripcio";
  private String estatCodiDescripcio;

  public static final String JSON_PROPERTY_ESTAT_ERROR = "estatError";
  private String estatError;

  public static final String JSON_PROPERTY_ESTAT_EXCEPCIO = "estatExcepcio";
  private String estatExcepcio;

  public static final String JSON_PROPERTY_LOGIN_TYPE = "loginType";
  private String loginType;

  public static final String JSON_PROPERTY_LOGIN_SUBTYPE = "loginSubtype";
  private String loginSubtype;

  public static final String JSON_PROPERTY_LOGIN_QAA = "loginQaa";
  private String loginQaa;

  public static final String JSON_PROPERTY_LOGIN_DATA = "loginData";
  private OffsetDateTime loginData;

  public static final String JSON_PROPERTY_LOGIN_ID = "loginId";
  private String loginId;

  public static final String JSON_PROPERTY_LOGIN_AUTH_METHOD = "loginAuthMethod";
  private String loginAuthMethod;

  public static final String JSON_PROPERTY_LOGIN_ADDITIONAL_PROPERTIES = "loginAdditionalProperties";
  private String loginAdditionalProperties;

  public static final String JSON_PROPERTY_LOCALITZACIO_IP = "localitzacioIp";
  private String localitzacioIp;

  public static final String JSON_PROPERTY_LOCALITZACIO_CODI_POSTAL = "localitzacioCodiPostal";
  private String localitzacioCodiPostal;

  public static final String JSON_PROPERTY_LOCALITZACIO_LATITUD = "localitzacioLatitud";
  private String localitzacioLatitud;

  public static final String JSON_PROPERTY_LOCALITZACIO_LONGITUD = "localitzacioLongitud";
  private String localitzacioLongitud;

  public static final String JSON_PROPERTY_LOCALITZACIO_CIUTAT = "localitzacioCiutat";
  private String localitzacioCiutat;

  public static final String JSON_PROPERTY_LOCALITZACIO_REGIO = "localitzacioRegio";
  private String localitzacioRegio;

  public static final String JSON_PROPERTY_LOCALITZACIO_PAIS = "localitzacioPais";
  private String localitzacioPais;

  public static final String JSON_PROPERTY_FIRMA_REASON = "firmaReason";
  private String firmaReason;

  public static final String JSON_PROPERTY_FIRMA_IDIOMA_DOCUMENT = "firmaIdiomaDocument";
  private String firmaIdiomaDocument;

  public static final String JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL = "firmaTipusDocumental";
  private Integer firmaTipusDocumental;

  public static final String JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL_DESCRIPCIO = "firmaTipusDocumentalDescripcio";
  private String firmaTipusDocumentalDescripcio;

  public static final String JSON_PROPERTY_FITXER_ORIGINAL = "fitxerOriginal";
  private EvidenciaFile fitxerOriginal;

  public static final String JSON_PROPERTY_FITXER_ADAPTAT = "fitxerAdaptat";
  private EvidenciaFile fitxerAdaptat;

  public static final String JSON_PROPERTY_FITXER_SIGNAT = "fitxerSignat";
  private EvidenciaFile fitxerSignat;

  public EvidenciaWs() {
  }

  public EvidenciaWs evidenciaID(Long evidenciaID) {
    
    this.evidenciaID = evidenciaID;
    return this;
  }

   /**
   * Identificador únic de l&#39;evidència.
   * @return evidenciaID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVIDENCIA_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEvidenciaID() {
    return evidenciaID;
  }


  @JsonProperty(JSON_PROPERTY_EVIDENCIA_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvidenciaID(Long evidenciaID) {
    this.evidenciaID = evidenciaID;
  }


  public EvidenciaWs nom(String nom) {
    
    this.nom = nom;
    return this;
  }

   /**
   * Nom descriptiu de l&#39;evidència.
   * @return nom
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(String nom) {
    this.nom = nom;
  }


  public EvidenciaWs personaNom(String personaNom) {
    
    this.personaNom = personaNom;
    return this;
  }

   /**
   * Nom de la persona
   * @return personaNom
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERSONA_NOM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPersonaNom() {
    return personaNom;
  }


  @JsonProperty(JSON_PROPERTY_PERSONA_NOM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonaNom(String personaNom) {
    this.personaNom = personaNom;
  }


  public EvidenciaWs personaLlinatge1(String personaLlinatge1) {
    
    this.personaLlinatge1 = personaLlinatge1;
    return this;
  }

   /**
   * Primer llinatge de la persona
   * @return personaLlinatge1
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERSONA_LLINATGE1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPersonaLlinatge1() {
    return personaLlinatge1;
  }


  @JsonProperty(JSON_PROPERTY_PERSONA_LLINATGE1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonaLlinatge1(String personaLlinatge1) {
    this.personaLlinatge1 = personaLlinatge1;
  }


  public EvidenciaWs personaLlinatge2(String personaLlinatge2) {
    
    this.personaLlinatge2 = personaLlinatge2;
    return this;
  }

   /**
   * Segon llintge de la persona
   * @return personaLlinatge2
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERSONA_LLINATGE2)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPersonaLlinatge2() {
    return personaLlinatge2;
  }


  @JsonProperty(JSON_PROPERTY_PERSONA_LLINATGE2)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonaLlinatge2(String personaLlinatge2) {
    this.personaLlinatge2 = personaLlinatge2;
  }


  public EvidenciaWs personaNif(String personaNif) {
    
    this.personaNif = personaNif;
    return this;
  }

   /**
   * Nif de la persona
   * @return personaNif
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERSONA_NIF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPersonaNif() {
    return personaNif;
  }


  @JsonProperty(JSON_PROPERTY_PERSONA_NIF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonaNif(String personaNif) {
    this.personaNif = personaNif;
  }


  public EvidenciaWs personaEmail(String personaEmail) {
    
    this.personaEmail = personaEmail;
    return this;
  }

   /**
   * Email de la persona
   * @return personaEmail
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERSONA_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPersonaEmail() {
    return personaEmail;
  }


  @JsonProperty(JSON_PROPERTY_PERSONA_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPersonaEmail(String personaEmail) {
    this.personaEmail = personaEmail;
  }


  public EvidenciaWs personaMobil(String personaMobil) {
    
    this.personaMobil = personaMobil;
    return this;
  }

   /**
   * Mòbil de la persona
   * @return personaMobil
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERSONA_MOBIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPersonaMobil() {
    return personaMobil;
  }


  @JsonProperty(JSON_PROPERTY_PERSONA_MOBIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPersonaMobil(String personaMobil) {
    this.personaMobil = personaMobil;
  }


  public EvidenciaWs dataInici(OffsetDateTime dataInici) {
    
    this.dataInici = dataInici;
    return this;
  }

   /**
   * Data de creació de l&#39;evidència
   * @return dataInici
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATA_INICI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getDataInici() {
    return dataInici;
  }


  @JsonProperty(JSON_PROPERTY_DATA_INICI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDataInici(OffsetDateTime dataInici) {
    this.dataInici = dataInici;
  }


  public EvidenciaWs dataFi(OffsetDateTime dataFi) {
    
    this.dataFi = dataFi;
    return this;
  }

   /**
   * Data final de l&#39;evidència
   * @return dataFi
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_FI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDataFi() {
    return dataFi;
  }


  @JsonProperty(JSON_PROPERTY_DATA_FI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataFi(OffsetDateTime dataFi) {
    this.dataFi = dataFi;
  }


  public EvidenciaWs estatCodi(Integer estatCodi) {
    
    this.estatCodi = estatCodi;
    return this;
  }

   /**
   * Estat en que ha finalitzat l&#39;evidència. Posibles estats:      public static final int EVIDENCIA_ESTAT_CODI_ERROR &#x3D; -1;      public static final int EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO &#x3D; 1;      public static final int EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN &#x3D; 2;      public static final int EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA &#x3D; 3;      public static final int EVIDENCIA_ESTAT_CODI_SIGNAT &#x3D; 10;
   * @return estatCodi
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT_CODI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEstatCodi() {
    return estatCodi;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT_CODI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstatCodi(Integer estatCodi) {
    this.estatCodi = estatCodi;
  }


  public EvidenciaWs estatCodiDescripcio(String estatCodiDescripcio) {
    
    this.estatCodiDescripcio = estatCodiDescripcio;
    return this;
  }

   /**
   * Descripció del camp estatCodi
   * @return estatCodiDescripcio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT_CODI_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEstatCodiDescripcio() {
    return estatCodiDescripcio;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT_CODI_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstatCodiDescripcio(String estatCodiDescripcio) {
    this.estatCodiDescripcio = estatCodiDescripcio;
  }


  public EvidenciaWs estatError(String estatError) {
    
    this.estatError = estatError;
    return this;
  }

   /**
   * Missatge de l&#39;error
   * @return estatError
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEstatError() {
    return estatError;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstatError(String estatError) {
    this.estatError = estatError;
  }


  public EvidenciaWs estatExcepcio(String estatExcepcio) {
    
    this.estatExcepcio = estatExcepcio;
    return this;
  }

   /**
   * Stacktrace de l&#39;excepció si n&#39;hi hagues
   * @return estatExcepcio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT_EXCEPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEstatExcepcio() {
    return estatExcepcio;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT_EXCEPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstatExcepcio(String estatExcepcio) {
    this.estatExcepcio = estatExcepcio;
  }


  public EvidenciaWs loginType(String loginType) {
    
    this.loginType = loginType;
    return this;
  }

   /**
   * Tipus de Login
   * @return loginType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGIN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoginType() {
    return loginType;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoginType(String loginType) {
    this.loginType = loginType;
  }


  public EvidenciaWs loginSubtype(String loginSubtype) {
    
    this.loginSubtype = loginSubtype;
    return this;
  }

   /**
   * Subtipus de login
   * @return loginSubtype
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGIN_SUBTYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoginSubtype() {
    return loginSubtype;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_SUBTYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoginSubtype(String loginSubtype) {
    this.loginSubtype = loginSubtype;
  }


  public EvidenciaWs loginQaa(String loginQaa) {
    
    this.loginQaa = loginQaa;
    return this;
  }

   /**
   * Nivell des eguretat de login
   * @return loginQaa
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGIN_QAA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoginQaa() {
    return loginQaa;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_QAA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoginQaa(String loginQaa) {
    this.loginQaa = loginQaa;
  }


  public EvidenciaWs loginData(OffsetDateTime loginData) {
    
    this.loginData = loginData;
    return this;
  }

   /**
   * Data de realització del login
   * @return loginData
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGIN_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getLoginData() {
    return loginData;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoginData(OffsetDateTime loginData) {
    this.loginData = loginData;
  }


  public EvidenciaWs loginId(String loginId) {
    
    this.loginId = loginId;
    return this;
  }

   /**
   * Identificador del login realitzat.
   * @return loginId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGIN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoginId() {
    return loginId;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoginId(String loginId) {
    this.loginId = loginId;
  }


  public EvidenciaWs loginAuthMethod(String loginAuthMethod) {
    
    this.loginAuthMethod = loginAuthMethod;
    return this;
  }

   /**
   * Get loginAuthMethod
   * @return loginAuthMethod
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGIN_AUTH_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoginAuthMethod() {
    return loginAuthMethod;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_AUTH_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoginAuthMethod(String loginAuthMethod) {
    this.loginAuthMethod = loginAuthMethod;
  }


  public EvidenciaWs loginAdditionalProperties(String loginAdditionalProperties) {
    
    this.loginAdditionalProperties = loginAdditionalProperties;
    return this;
  }

   /**
   * Get loginAdditionalProperties
   * @return loginAdditionalProperties
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGIN_ADDITIONAL_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoginAdditionalProperties() {
    return loginAdditionalProperties;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_ADDITIONAL_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoginAdditionalProperties(String loginAdditionalProperties) {
    this.loginAdditionalProperties = loginAdditionalProperties;
  }


  public EvidenciaWs localitzacioIp(String localitzacioIp) {
    
    this.localitzacioIp = localitzacioIp;
    return this;
  }

   /**
   * IP des d&#39;on està connectat el ciutadà
   * @return localitzacioIp
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioIp() {
    return localitzacioIp;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioIp(String localitzacioIp) {
    this.localitzacioIp = localitzacioIp;
  }


  public EvidenciaWs localitzacioCodiPostal(String localitzacioCodiPostal) {
    
    this.localitzacioCodiPostal = localitzacioCodiPostal;
    return this;
  }

   /**
   * Codi postal des d&#39;on està connectat el ciutadà.
   * @return localitzacioCodiPostal
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_CODI_POSTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioCodiPostal() {
    return localitzacioCodiPostal;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_CODI_POSTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioCodiPostal(String localitzacioCodiPostal) {
    this.localitzacioCodiPostal = localitzacioCodiPostal;
  }


  public EvidenciaWs localitzacioLatitud(String localitzacioLatitud) {
    
    this.localitzacioLatitud = localitzacioLatitud;
    return this;
  }

   /**
   * Latitud des d&#39;on està connectat el ciutadà.
   * @return localitzacioLatitud
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_LATITUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioLatitud() {
    return localitzacioLatitud;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_LATITUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioLatitud(String localitzacioLatitud) {
    this.localitzacioLatitud = localitzacioLatitud;
  }


  public EvidenciaWs localitzacioLongitud(String localitzacioLongitud) {
    
    this.localitzacioLongitud = localitzacioLongitud;
    return this;
  }

   /**
   * Longitud des d&#39;on està connectat el ciutadà.
   * @return localitzacioLongitud
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_LONGITUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioLongitud() {
    return localitzacioLongitud;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_LONGITUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioLongitud(String localitzacioLongitud) {
    this.localitzacioLongitud = localitzacioLongitud;
  }


  public EvidenciaWs localitzacioCiutat(String localitzacioCiutat) {
    
    this.localitzacioCiutat = localitzacioCiutat;
    return this;
  }

   /**
   * Localitat des d&#39;on està connectat el ciutadà.
   * @return localitzacioCiutat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_CIUTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioCiutat() {
    return localitzacioCiutat;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_CIUTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioCiutat(String localitzacioCiutat) {
    this.localitzacioCiutat = localitzacioCiutat;
  }


  public EvidenciaWs localitzacioRegio(String localitzacioRegio) {
    
    this.localitzacioRegio = localitzacioRegio;
    return this;
  }

   /**
   * Regió (Si és Espanya Comunitat Autonoma) des d&#39;on està connectat el ciutadà.
   * @return localitzacioRegio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_REGIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioRegio() {
    return localitzacioRegio;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_REGIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioRegio(String localitzacioRegio) {
    this.localitzacioRegio = localitzacioRegio;
  }


  public EvidenciaWs localitzacioPais(String localitzacioPais) {
    
    this.localitzacioPais = localitzacioPais;
    return this;
  }

   /**
   * Pais des d&#39;on està connectat el ciutadà.
   * @return localitzacioPais
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_PAIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioPais() {
    return localitzacioPais;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_PAIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioPais(String localitzacioPais) {
    this.localitzacioPais = localitzacioPais;
  }


  public EvidenciaWs firmaReason(String firmaReason) {
    
    this.firmaReason = firmaReason;
    return this;
  }

   /**
   * Raó de firma.
   * @return firmaReason
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRMA_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirmaReason() {
    return firmaReason;
  }


  @JsonProperty(JSON_PROPERTY_FIRMA_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirmaReason(String firmaReason) {
    this.firmaReason = firmaReason;
  }


  public EvidenciaWs firmaIdiomaDocument(String firmaIdiomaDocument) {
    
    this.firmaIdiomaDocument = firmaIdiomaDocument;
    return this;
  }

   /**
   * Idioma en que està escrit el document.
   * @return firmaIdiomaDocument
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRMA_IDIOMA_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirmaIdiomaDocument() {
    return firmaIdiomaDocument;
  }


  @JsonProperty(JSON_PROPERTY_FIRMA_IDIOMA_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirmaIdiomaDocument(String firmaIdiomaDocument) {
    this.firmaIdiomaDocument = firmaIdiomaDocument;
  }


  public EvidenciaWs firmaTipusDocumental(Integer firmaTipusDocumental) {
    
    this.firmaTipusDocumental = firmaTipusDocumental;
    return this;
  }

   /**
   * Tipus documental de la Firma. Veure https://administracionelectronica.gob.es/pae_Home/dam/jcr:26d90313-7af0-4f69-9d62-c853d55d7627/Esquema_Metadatos_e-EMGDE_2016.pdf
   * @return firmaTipusDocumental
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getFirmaTipusDocumental() {
    return firmaTipusDocumental;
  }


  @JsonProperty(JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirmaTipusDocumental(Integer firmaTipusDocumental) {
    this.firmaTipusDocumental = firmaTipusDocumental;
  }


  public EvidenciaWs firmaTipusDocumentalDescripcio(String firmaTipusDocumentalDescripcio) {
    
    this.firmaTipusDocumentalDescripcio = firmaTipusDocumentalDescripcio;
    return this;
  }

   /**
   * DescripcioTipus documental de la Firma.Per exemple per 1 retorna &#39;Resolución(TD01)&#39;
   * @return firmaTipusDocumentalDescripcio
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirmaTipusDocumentalDescripcio() {
    return firmaTipusDocumentalDescripcio;
  }


  @JsonProperty(JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirmaTipusDocumentalDescripcio(String firmaTipusDocumentalDescripcio) {
    this.firmaTipusDocumentalDescripcio = firmaTipusDocumentalDescripcio;
  }


  public EvidenciaWs fitxerOriginal(EvidenciaFile fitxerOriginal) {
    
    this.fitxerOriginal = fitxerOriginal;
    return this;
  }

   /**
   * Get fitxerOriginal
   * @return fitxerOriginal
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FITXER_ORIGINAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EvidenciaFile getFitxerOriginal() {
    return fitxerOriginal;
  }


  @JsonProperty(JSON_PROPERTY_FITXER_ORIGINAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFitxerOriginal(EvidenciaFile fitxerOriginal) {
    this.fitxerOriginal = fitxerOriginal;
  }


  public EvidenciaWs fitxerAdaptat(EvidenciaFile fitxerAdaptat) {
    
    this.fitxerAdaptat = fitxerAdaptat;
    return this;
  }

   /**
   * Get fitxerAdaptat
   * @return fitxerAdaptat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FITXER_ADAPTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EvidenciaFile getFitxerAdaptat() {
    return fitxerAdaptat;
  }


  @JsonProperty(JSON_PROPERTY_FITXER_ADAPTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFitxerAdaptat(EvidenciaFile fitxerAdaptat) {
    this.fitxerAdaptat = fitxerAdaptat;
  }


  public EvidenciaWs fitxerSignat(EvidenciaFile fitxerSignat) {
    
    this.fitxerSignat = fitxerSignat;
    return this;
  }

   /**
   * Get fitxerSignat
   * @return fitxerSignat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FITXER_SIGNAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EvidenciaFile getFitxerSignat() {
    return fitxerSignat;
  }


  @JsonProperty(JSON_PROPERTY_FITXER_SIGNAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFitxerSignat(EvidenciaFile fitxerSignat) {
    this.fitxerSignat = fitxerSignat;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvidenciaWs evidenciaWs = (EvidenciaWs) o;
    return Objects.equals(this.evidenciaID, evidenciaWs.evidenciaID) &&
        Objects.equals(this.nom, evidenciaWs.nom) &&
        Objects.equals(this.personaNom, evidenciaWs.personaNom) &&
        Objects.equals(this.personaLlinatge1, evidenciaWs.personaLlinatge1) &&
        Objects.equals(this.personaLlinatge2, evidenciaWs.personaLlinatge2) &&
        Objects.equals(this.personaNif, evidenciaWs.personaNif) &&
        Objects.equals(this.personaEmail, evidenciaWs.personaEmail) &&
        Objects.equals(this.personaMobil, evidenciaWs.personaMobil) &&
        Objects.equals(this.dataInici, evidenciaWs.dataInici) &&
        Objects.equals(this.dataFi, evidenciaWs.dataFi) &&
        Objects.equals(this.estatCodi, evidenciaWs.estatCodi) &&
        Objects.equals(this.estatCodiDescripcio, evidenciaWs.estatCodiDescripcio) &&
        Objects.equals(this.estatError, evidenciaWs.estatError) &&
        Objects.equals(this.estatExcepcio, evidenciaWs.estatExcepcio) &&
        Objects.equals(this.loginType, evidenciaWs.loginType) &&
        Objects.equals(this.loginSubtype, evidenciaWs.loginSubtype) &&
        Objects.equals(this.loginQaa, evidenciaWs.loginQaa) &&
        Objects.equals(this.loginData, evidenciaWs.loginData) &&
        Objects.equals(this.loginId, evidenciaWs.loginId) &&
        Objects.equals(this.loginAuthMethod, evidenciaWs.loginAuthMethod) &&
        Objects.equals(this.loginAdditionalProperties, evidenciaWs.loginAdditionalProperties) &&
        Objects.equals(this.localitzacioIp, evidenciaWs.localitzacioIp) &&
        Objects.equals(this.localitzacioCodiPostal, evidenciaWs.localitzacioCodiPostal) &&
        Objects.equals(this.localitzacioLatitud, evidenciaWs.localitzacioLatitud) &&
        Objects.equals(this.localitzacioLongitud, evidenciaWs.localitzacioLongitud) &&
        Objects.equals(this.localitzacioCiutat, evidenciaWs.localitzacioCiutat) &&
        Objects.equals(this.localitzacioRegio, evidenciaWs.localitzacioRegio) &&
        Objects.equals(this.localitzacioPais, evidenciaWs.localitzacioPais) &&
        Objects.equals(this.firmaReason, evidenciaWs.firmaReason) &&
        Objects.equals(this.firmaIdiomaDocument, evidenciaWs.firmaIdiomaDocument) &&
        Objects.equals(this.firmaTipusDocumental, evidenciaWs.firmaTipusDocumental) &&
        Objects.equals(this.firmaTipusDocumentalDescripcio, evidenciaWs.firmaTipusDocumentalDescripcio) &&
        Objects.equals(this.fitxerOriginal, evidenciaWs.fitxerOriginal) &&
        Objects.equals(this.fitxerAdaptat, evidenciaWs.fitxerAdaptat) &&
        Objects.equals(this.fitxerSignat, evidenciaWs.fitxerSignat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(evidenciaID, nom, personaNom, personaLlinatge1, personaLlinatge2, personaNif, personaEmail, personaMobil, dataInici, dataFi, estatCodi, estatCodiDescripcio, estatError, estatExcepcio, loginType, loginSubtype, loginQaa, loginData, loginId, loginAuthMethod, loginAdditionalProperties, localitzacioIp, localitzacioCodiPostal, localitzacioLatitud, localitzacioLongitud, localitzacioCiutat, localitzacioRegio, localitzacioPais, firmaReason, firmaIdiomaDocument, firmaTipusDocumental, firmaTipusDocumentalDescripcio, fitxerOriginal, fitxerAdaptat, fitxerSignat);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvidenciaWs {\n");
    sb.append("    evidenciaID: ").append(toIndentedString(evidenciaID)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    personaNom: ").append(toIndentedString(personaNom)).append("\n");
    sb.append("    personaLlinatge1: ").append(toIndentedString(personaLlinatge1)).append("\n");
    sb.append("    personaLlinatge2: ").append(toIndentedString(personaLlinatge2)).append("\n");
    sb.append("    personaNif: ").append(toIndentedString(personaNif)).append("\n");
    sb.append("    personaEmail: ").append(toIndentedString(personaEmail)).append("\n");
    sb.append("    personaMobil: ").append(toIndentedString(personaMobil)).append("\n");
    sb.append("    dataInici: ").append(toIndentedString(dataInici)).append("\n");
    sb.append("    dataFi: ").append(toIndentedString(dataFi)).append("\n");
    sb.append("    estatCodi: ").append(toIndentedString(estatCodi)).append("\n");
    sb.append("    estatCodiDescripcio: ").append(toIndentedString(estatCodiDescripcio)).append("\n");
    sb.append("    estatError: ").append(toIndentedString(estatError)).append("\n");
    sb.append("    estatExcepcio: ").append(toIndentedString(estatExcepcio)).append("\n");
    sb.append("    loginType: ").append(toIndentedString(loginType)).append("\n");
    sb.append("    loginSubtype: ").append(toIndentedString(loginSubtype)).append("\n");
    sb.append("    loginQaa: ").append(toIndentedString(loginQaa)).append("\n");
    sb.append("    loginData: ").append(toIndentedString(loginData)).append("\n");
    sb.append("    loginId: ").append(toIndentedString(loginId)).append("\n");
    sb.append("    loginAuthMethod: ").append(toIndentedString(loginAuthMethod)).append("\n");
    sb.append("    loginAdditionalProperties: ").append(toIndentedString(loginAdditionalProperties)).append("\n");
    sb.append("    localitzacioIp: ").append(toIndentedString(localitzacioIp)).append("\n");
    sb.append("    localitzacioCodiPostal: ").append(toIndentedString(localitzacioCodiPostal)).append("\n");
    sb.append("    localitzacioLatitud: ").append(toIndentedString(localitzacioLatitud)).append("\n");
    sb.append("    localitzacioLongitud: ").append(toIndentedString(localitzacioLongitud)).append("\n");
    sb.append("    localitzacioCiutat: ").append(toIndentedString(localitzacioCiutat)).append("\n");
    sb.append("    localitzacioRegio: ").append(toIndentedString(localitzacioRegio)).append("\n");
    sb.append("    localitzacioPais: ").append(toIndentedString(localitzacioPais)).append("\n");
    sb.append("    firmaReason: ").append(toIndentedString(firmaReason)).append("\n");
    sb.append("    firmaIdiomaDocument: ").append(toIndentedString(firmaIdiomaDocument)).append("\n");
    sb.append("    firmaTipusDocumental: ").append(toIndentedString(firmaTipusDocumental)).append("\n");
    sb.append("    firmaTipusDocumentalDescripcio: ").append(toIndentedString(firmaTipusDocumentalDescripcio)).append("\n");
    sb.append("    fitxerOriginal: ").append(toIndentedString(fitxerOriginal)).append("\n");
    sb.append("    fitxerAdaptat: ").append(toIndentedString(fitxerAdaptat)).append("\n");
    sb.append("    fitxerSignat: ").append(toIndentedString(fitxerSignat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

