/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.evidenciesib.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * EvidenciaFile
 */


public class EvidenciaFile {
  @JsonProperty("document")
  private byte[] document = null;

  @JsonProperty("nom")
  private String nom = null;

  @JsonProperty("mime")
  private String mime = null;

  @JsonProperty("tamany")
  private Long tamany = null;

  @JsonProperty("descripcio")
  private String descripcio = null;

  public EvidenciaFile document(byte[] document) {
    this.document = document;
    return this;
  }

   /**
   * Get document
   * @return document
  **/
  @Schema(description = "")
  public byte[] getDocument() {
    return document;
  }

  public void setDocument(byte[] document) {
    this.document = document;
  }

  public EvidenciaFile nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Get nom
   * @return nom
  **/
  @Schema(description = "")
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }

  public EvidenciaFile mime(String mime) {
    this.mime = mime;
    return this;
  }

   /**
   * Get mime
   * @return mime
  **/
  @Schema(description = "")
  public String getMime() {
    return mime;
  }

  public void setMime(String mime) {
    this.mime = mime;
  }

  public EvidenciaFile tamany(Long tamany) {
    this.tamany = tamany;
    return this;
  }

   /**
   * Get tamany
   * @return tamany
  **/
  @Schema(description = "")
  public Long getTamany() {
    return tamany;
  }

  public void setTamany(Long tamany) {
    this.tamany = tamany;
  }

  public EvidenciaFile descripcio(String descripcio) {
    this.descripcio = descripcio;
    return this;
  }

   /**
   * Get descripcio
   * @return descripcio
  **/
  @Schema(description = "")
  public String getDescripcio() {
    return descripcio;
  }

  public void setDescripcio(String descripcio) {
    this.descripcio = descripcio;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvidenciaFile evidenciaFile = (EvidenciaFile) o;
    return Arrays.equals(this.document, evidenciaFile.document) &&
        Objects.equals(this.nom, evidenciaFile.nom) &&
        Objects.equals(this.mime, evidenciaFile.mime) &&
        Objects.equals(this.tamany, evidenciaFile.tamany) &&
        Objects.equals(this.descripcio, evidenciaFile.descripcio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(document), nom, mime, tamany, descripcio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvidenciaFile {\n");
    
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    mime: ").append(toIndentedString(mime)).append("\n");
    sb.append("    tamany: ").append(toIndentedString(tamany)).append("\n");
    sb.append("    descripcio: ").append(toIndentedString(descripcio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
