/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.evidenciesib.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.evidenciesib.apiexterna.client.model.EvidenciaFile;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Estructura de dades a enviar al servidor per iniciar un procés d&#x27;Evidències
 */
@Schema(description = "Estructura de dades a enviar al servidor per iniciar un procés d'Evidències")

public class EvidenciaStartRequest {
  @JsonProperty("titolEvidencia")
  private String titolEvidencia = null;

  @JsonProperty("personaNom")
  private String personaNom = null;

  @JsonProperty("personaLlinatge1")
  private String personaLlinatge1 = null;

  @JsonProperty("personaLlinatge2")
  private String personaLlinatge2 = null;

  @JsonProperty("personaNif")
  private String personaNif = null;

  @JsonProperty("personaEmail")
  private String personaEmail = null;

  @JsonProperty("personaMobil")
  private String personaMobil = null;

  @JsonProperty("raoDeLaFirma")
  private String raoDeLaFirma = null;

  @JsonProperty("languageDocument")
  private String languageDocument = "ca";

  @JsonProperty("documentASignar")
  private EvidenciaFile documentASignar = null;

  @JsonProperty("callBackUrl")
  private String callBackUrl = null;

  @JsonProperty("languageUI")
  private String languageUI = "ca";

  public EvidenciaStartRequest titolEvidencia(String titolEvidencia) {
    this.titolEvidencia = titolEvidencia;
    return this;
  }

   /**
   * Titol descriptiu de l&#x27;evidència que es durà a terme
   * @return titolEvidencia
  **/
  @Schema(required = true, description = "Titol descriptiu de l'evidència que es durà a terme")
  public String getTitolEvidencia() {
    return titolEvidencia;
  }

  public void setTitolEvidencia(String titolEvidencia) {
    this.titolEvidencia = titolEvidencia;
  }

  public EvidenciaStartRequest personaNom(String personaNom) {
    this.personaNom = personaNom;
    return this;
  }

   /**
   * Nom de la persona
   * @return personaNom
  **/
  @Schema(required = true, description = "Nom de la persona")
  public String getPersonaNom() {
    return personaNom;
  }

  public void setPersonaNom(String personaNom) {
    this.personaNom = personaNom;
  }

  public EvidenciaStartRequest personaLlinatge1(String personaLlinatge1) {
    this.personaLlinatge1 = personaLlinatge1;
    return this;
  }

   /**
   * Primer llinatge de la persona
   * @return personaLlinatge1
  **/
  @Schema(required = true, description = "Primer llinatge de la persona")
  public String getPersonaLlinatge1() {
    return personaLlinatge1;
  }

  public void setPersonaLlinatge1(String personaLlinatge1) {
    this.personaLlinatge1 = personaLlinatge1;
  }

  public EvidenciaStartRequest personaLlinatge2(String personaLlinatge2) {
    this.personaLlinatge2 = personaLlinatge2;
    return this;
  }

   /**
   * Segon llintge de la persona
   * @return personaLlinatge2
  **/
  @Schema(required = true, description = "Segon llintge de la persona")
  public String getPersonaLlinatge2() {
    return personaLlinatge2;
  }

  public void setPersonaLlinatge2(String personaLlinatge2) {
    this.personaLlinatge2 = personaLlinatge2;
  }

  public EvidenciaStartRequest personaNif(String personaNif) {
    this.personaNif = personaNif;
    return this;
  }

   /**
   * Nif de la persona
   * @return personaNif
  **/
  @Schema(required = true, description = "Nif de la persona")
  public String getPersonaNif() {
    return personaNif;
  }

  public void setPersonaNif(String personaNif) {
    this.personaNif = personaNif;
  }

  public EvidenciaStartRequest personaEmail(String personaEmail) {
    this.personaEmail = personaEmail;
    return this;
  }

   /**
   * Correu electrònic de la persona
   * @return personaEmail
  **/
  @Schema(description = "Correu electrònic de la persona")
  public String getPersonaEmail() {
    return personaEmail;
  }

  public void setPersonaEmail(String personaEmail) {
    this.personaEmail = personaEmail;
  }

  public EvidenciaStartRequest personaMobil(String personaMobil) {
    this.personaMobil = personaMobil;
    return this;
  }

   /**
   * Mòbil de la persona
   * @return personaMobil
  **/
  @Schema(description = "Mòbil de la persona")
  public String getPersonaMobil() {
    return personaMobil;
  }

  public void setPersonaMobil(String personaMobil) {
    this.personaMobil = personaMobil;
  }

  public EvidenciaStartRequest raoDeLaFirma(String raoDeLaFirma) {
    this.raoDeLaFirma = raoDeLaFirma;
    return this;
  }

   /**
   * Raó per la qual es requereix aquesta signatura
   * @return raoDeLaFirma
  **/
  @Schema(required = true, description = "Raó per la qual es requereix aquesta signatura")
  public String getRaoDeLaFirma() {
    return raoDeLaFirma;
  }

  public void setRaoDeLaFirma(String raoDeLaFirma) {
    this.raoDeLaFirma = raoDeLaFirma;
  }

  public EvidenciaStartRequest languageDocument(String languageDocument) {
    this.languageDocument = languageDocument;
    return this;
  }

   /**
   * Idioma del document en ISO 639-1. Valors permesos &#x27;ca&#x27; i &#x27;es&#x27;
   * @return languageDocument
  **/
  @Schema(example = "ca", required = true, description = "Idioma del document en ISO 639-1. Valors permesos 'ca' i 'es'")
  public String getLanguageDocument() {
    return languageDocument;
  }

  public void setLanguageDocument(String languageDocument) {
    this.languageDocument = languageDocument;
  }

  public EvidenciaStartRequest documentASignar(EvidenciaFile documentASignar) {
    this.documentASignar = documentASignar;
    return this;
  }

   /**
   * Get documentASignar
   * @return documentASignar
  **/
  @Schema(required = true, description = "")
  public EvidenciaFile getDocumentASignar() {
    return documentASignar;
  }

  public void setDocumentASignar(EvidenciaFile documentASignar) {
    this.documentASignar = documentASignar;
  }

  public EvidenciaStartRequest callBackUrl(String callBackUrl) {
    this.callBackUrl = callBackUrl;
    return this;
  }

   /**
   * URL de retorn quan el proces d&#x27;evidències hagi acabat. A la URL la cadena {0} es substituirà per l&#x27;identificador de l&#x27;evidència (evidenciaID)
   * @return callBackUrl
  **/
  @Schema(example = "http://host:port/myappback/mycallbackcontroller/callbackevidencies?evidenciaid={0}", required = true, description = "URL de retorn quan el proces d'evidències hagi acabat. A la URL la cadena {0} es substituirà per l'identificador de l'evidència (evidenciaID)")
  public String getCallBackUrl() {
    return callBackUrl;
  }

  public void setCallBackUrl(String callBackUrl) {
    this.callBackUrl = callBackUrl;
  }

  public EvidenciaStartRequest languageUI(String languageUI) {
    this.languageUI = languageUI;
    return this;
  }

   /**
   * Idioma del missatges d&#x27;error en format ISO 639-1. Valors permesos &#x27;ca&#x27; i &#x27;es&#x27;
   * @return languageUI
  **/
  @Schema(example = "ca", required = true, description = "Idioma del missatges d'error en format ISO 639-1. Valors permesos 'ca' i 'es'")
  public String getLanguageUI() {
    return languageUI;
  }

  public void setLanguageUI(String languageUI) {
    this.languageUI = languageUI;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvidenciaStartRequest evidenciaStartRequest = (EvidenciaStartRequest) o;
    return Objects.equals(this.titolEvidencia, evidenciaStartRequest.titolEvidencia) &&
        Objects.equals(this.personaNom, evidenciaStartRequest.personaNom) &&
        Objects.equals(this.personaLlinatge1, evidenciaStartRequest.personaLlinatge1) &&
        Objects.equals(this.personaLlinatge2, evidenciaStartRequest.personaLlinatge2) &&
        Objects.equals(this.personaNif, evidenciaStartRequest.personaNif) &&
        Objects.equals(this.personaEmail, evidenciaStartRequest.personaEmail) &&
        Objects.equals(this.personaMobil, evidenciaStartRequest.personaMobil) &&
        Objects.equals(this.raoDeLaFirma, evidenciaStartRequest.raoDeLaFirma) &&
        Objects.equals(this.languageDocument, evidenciaStartRequest.languageDocument) &&
        Objects.equals(this.documentASignar, evidenciaStartRequest.documentASignar) &&
        Objects.equals(this.callBackUrl, evidenciaStartRequest.callBackUrl) &&
        Objects.equals(this.languageUI, evidenciaStartRequest.languageUI);
  }

  @Override
  public int hashCode() {
    return Objects.hash(titolEvidencia, personaNom, personaLlinatge1, personaLlinatge2, personaNif, personaEmail, personaMobil, raoDeLaFirma, languageDocument, documentASignar, callBackUrl, languageUI);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvidenciaStartRequest {\n");
    
    sb.append("    titolEvidencia: ").append(toIndentedString(titolEvidencia)).append("\n");
    sb.append("    personaNom: ").append(toIndentedString(personaNom)).append("\n");
    sb.append("    personaLlinatge1: ").append(toIndentedString(personaLlinatge1)).append("\n");
    sb.append("    personaLlinatge2: ").append(toIndentedString(personaLlinatge2)).append("\n");
    sb.append("    personaNif: ").append(toIndentedString(personaNif)).append("\n");
    sb.append("    personaEmail: ").append(toIndentedString(personaEmail)).append("\n");
    sb.append("    personaMobil: ").append(toIndentedString(personaMobil)).append("\n");
    sb.append("    raoDeLaFirma: ").append(toIndentedString(raoDeLaFirma)).append("\n");
    sb.append("    languageDocument: ").append(toIndentedString(languageDocument)).append("\n");
    sb.append("    documentASignar: ").append(toIndentedString(documentASignar)).append("\n");
    sb.append("    callBackUrl: ").append(toIndentedString(callBackUrl)).append("\n");
    sb.append("    languageUI: ").append(toIndentedString(languageUI)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
