/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.evidenciesib.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.evidenciesib.apiexterna.client.model.EvidenciaFile;
import io.swagger.v3.oas.annotations.media.Schema;
import org.joda.time.DateTime;
/**
 * Elements retornats
 */
@Schema(description = "Elements retornats")

public class EvidenciaWs {
  @JsonProperty("evidenciaID")
  private Long evidenciaID = null;

  @JsonProperty("nom")
  private String nom = null;

  @JsonProperty("personaNom")
  private String personaNom = null;

  @JsonProperty("personaLlinatge1")
  private String personaLlinatge1 = null;

  @JsonProperty("personaLlinatge2")
  private String personaLlinatge2 = null;

  @JsonProperty("personaNif")
  private String personaNif = null;

  @JsonProperty("personaEmail")
  private String personaEmail = null;

  @JsonProperty("personaMobil")
  private String personaMobil = null;

  @JsonProperty("dataInici")
  private DateTime dataInici = null;

  @JsonProperty("dataFi")
  private DateTime dataFi = null;

  @JsonProperty("estatCodi")
  private Integer estatCodi = null;

  @JsonProperty("estatCodiDescripcio")
  private String estatCodiDescripcio = null;

  @JsonProperty("estatError")
  private String estatError = null;

  @JsonProperty("estatExcepcio")
  private String estatExcepcio = null;

  @JsonProperty("loginType")
  private Integer loginType = null;

  @JsonProperty("loginTypeDescription")
  private String loginTypeDescription = null;

  @JsonProperty("loginSubtype")
  private String loginSubtype = null;

  @JsonProperty("loginQaa")
  private String loginQaa = null;

  @JsonProperty("loginData")
  private DateTime loginData = null;

  @JsonProperty("loginId")
  private String loginId = null;

  @JsonProperty("loginAuthMethod")
  private String loginAuthMethod = null;

  @JsonProperty("loginAdditionalProperties")
  private String loginAdditionalProperties = null;

  @JsonProperty("localitzacioIp")
  private String localitzacioIp = null;

  @JsonProperty("localitzacioCodiPostal")
  private String localitzacioCodiPostal = null;

  @JsonProperty("localitzacioLatitud")
  private String localitzacioLatitud = null;

  @JsonProperty("localitzacioLongitud")
  private String localitzacioLongitud = null;

  @JsonProperty("localitzacioCiutat")
  private String localitzacioCiutat = null;

  @JsonProperty("localitzacioRegio")
  private String localitzacioRegio = null;

  @JsonProperty("localitzacioPais")
  private String localitzacioPais = null;

  @JsonProperty("firmaReason")
  private String firmaReason = null;

  @JsonProperty("firmaIdiomaDocument")
  private String firmaIdiomaDocument = null;

  @JsonProperty("firmaTipusDocumental")
  private Integer firmaTipusDocumental = null;

  @JsonProperty("firmaTipusDocumentalDescripcio")
  private String firmaTipusDocumentalDescripcio = null;

  @JsonProperty("fitxerOriginal")
  private EvidenciaFile fitxerOriginal = null;

  @JsonProperty("fitxerAdaptat")
  private EvidenciaFile fitxerAdaptat = null;

  @JsonProperty("fitxerSignat")
  private EvidenciaFile fitxerSignat = null;

  public EvidenciaWs evidenciaID(Long evidenciaID) {
    this.evidenciaID = evidenciaID;
    return this;
  }

   /**
   * Identificador únic de l&#x27;evidència.
   * @return evidenciaID
  **/
  @Schema(description = "Identificador únic de l'evidència.")
  public Long getEvidenciaID() {
    return evidenciaID;
  }

  public void setEvidenciaID(Long evidenciaID) {
    this.evidenciaID = evidenciaID;
  }

  public EvidenciaWs nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Nom descriptiu de l&#x27;evidència.
   * @return nom
  **/
  @Schema(description = "Nom descriptiu de l'evidència.")
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }

  public EvidenciaWs personaNom(String personaNom) {
    this.personaNom = personaNom;
    return this;
  }

   /**
   * Nom de la persona
   * @return personaNom
  **/
  @Schema(required = true, description = "Nom de la persona")
  public String getPersonaNom() {
    return personaNom;
  }

  public void setPersonaNom(String personaNom) {
    this.personaNom = personaNom;
  }

  public EvidenciaWs personaLlinatge1(String personaLlinatge1) {
    this.personaLlinatge1 = personaLlinatge1;
    return this;
  }

   /**
   * Primer llinatge de la persona
   * @return personaLlinatge1
  **/
  @Schema(required = true, description = "Primer llinatge de la persona")
  public String getPersonaLlinatge1() {
    return personaLlinatge1;
  }

  public void setPersonaLlinatge1(String personaLlinatge1) {
    this.personaLlinatge1 = personaLlinatge1;
  }

  public EvidenciaWs personaLlinatge2(String personaLlinatge2) {
    this.personaLlinatge2 = personaLlinatge2;
    return this;
  }

   /**
   * Segon llintge de la persona
   * @return personaLlinatge2
  **/
  @Schema(required = true, description = "Segon llintge de la persona")
  public String getPersonaLlinatge2() {
    return personaLlinatge2;
  }

  public void setPersonaLlinatge2(String personaLlinatge2) {
    this.personaLlinatge2 = personaLlinatge2;
  }

  public EvidenciaWs personaNif(String personaNif) {
    this.personaNif = personaNif;
    return this;
  }

   /**
   * Nif de la persona
   * @return personaNif
  **/
  @Schema(required = true, description = "Nif de la persona")
  public String getPersonaNif() {
    return personaNif;
  }

  public void setPersonaNif(String personaNif) {
    this.personaNif = personaNif;
  }

  public EvidenciaWs personaEmail(String personaEmail) {
    this.personaEmail = personaEmail;
    return this;
  }

   /**
   * Email de la persona
   * @return personaEmail
  **/
  @Schema(description = "Email de la persona")
  public String getPersonaEmail() {
    return personaEmail;
  }

  public void setPersonaEmail(String personaEmail) {
    this.personaEmail = personaEmail;
  }

  public EvidenciaWs personaMobil(String personaMobil) {
    this.personaMobil = personaMobil;
    return this;
  }

   /**
   * Mòbil de la persona
   * @return personaMobil
  **/
  @Schema(description = "Mòbil de la persona")
  public String getPersonaMobil() {
    return personaMobil;
  }

  public void setPersonaMobil(String personaMobil) {
    this.personaMobil = personaMobil;
  }

  public EvidenciaWs dataInici(DateTime dataInici) {
    this.dataInici = dataInici;
    return this;
  }

   /**
   * Data de creació de l&#x27;evidència
   * @return dataInici
  **/
  @Schema(required = true, description = "Data de creació de l'evidència")
  public DateTime getDataInici() {
    return dataInici;
  }

  public void setDataInici(DateTime dataInici) {
    this.dataInici = dataInici;
  }

  public EvidenciaWs dataFi(DateTime dataFi) {
    this.dataFi = dataFi;
    return this;
  }

   /**
   * Data final de l&#x27;evidència
   * @return dataFi
  **/
  @Schema(description = "Data final de l'evidència")
  public DateTime getDataFi() {
    return dataFi;
  }

  public void setDataFi(DateTime dataFi) {
    this.dataFi = dataFi;
  }

  public EvidenciaWs estatCodi(Integer estatCodi) {
    this.estatCodi = estatCodi;
    return this;
  }

   /**
   * Estat en que ha finalitzat l&#x27;evidència. Posibles estats:      public static final int EVIDENCIA_ESTAT_CODI_ERROR &#x3D; -1;      public static final int EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO &#x3D; 1;      public static final int EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN &#x3D; 2;      public static final int EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA &#x3D; 3;      public static final int EVIDENCIA_ESTAT_CODI_SIGNAT &#x3D; 10;
   * @return estatCodi
  **/
  @Schema(description = "Estat en que ha finalitzat l'evidència. Posibles estats:      public static final int EVIDENCIA_ESTAT_CODI_ERROR = -1;      public static final int EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO = 1;      public static final int EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN = 2;      public static final int EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA = 3;      public static final int EVIDENCIA_ESTAT_CODI_SIGNAT = 10;")
  public Integer getEstatCodi() {
    return estatCodi;
  }

  public void setEstatCodi(Integer estatCodi) {
    this.estatCodi = estatCodi;
  }

  public EvidenciaWs estatCodiDescripcio(String estatCodiDescripcio) {
    this.estatCodiDescripcio = estatCodiDescripcio;
    return this;
  }

   /**
   * Descripció del camp estatCodi
   * @return estatCodiDescripcio
  **/
  @Schema(description = "Descripció del camp estatCodi")
  public String getEstatCodiDescripcio() {
    return estatCodiDescripcio;
  }

  public void setEstatCodiDescripcio(String estatCodiDescripcio) {
    this.estatCodiDescripcio = estatCodiDescripcio;
  }

  public EvidenciaWs estatError(String estatError) {
    this.estatError = estatError;
    return this;
  }

   /**
   * Missatge de l&#x27;error
   * @return estatError
  **/
  @Schema(description = "Missatge de l'error")
  public String getEstatError() {
    return estatError;
  }

  public void setEstatError(String estatError) {
    this.estatError = estatError;
  }

  public EvidenciaWs estatExcepcio(String estatExcepcio) {
    this.estatExcepcio = estatExcepcio;
    return this;
  }

   /**
   * Stacktrace de l&#x27;excepció si n&#x27;hi hagues
   * @return estatExcepcio
  **/
  @Schema(description = "Stacktrace de l'excepció si n'hi hagues")
  public String getEstatExcepcio() {
    return estatExcepcio;
  }

  public void setEstatExcepcio(String estatExcepcio) {
    this.estatExcepcio = estatExcepcio;
  }

  public EvidenciaWs loginType(Integer loginType) {
    this.loginType = loginType;
    return this;
  }

   /**
   * Codi del Tipus de Login
   * @return loginType
  **/
  @Schema(required = true, description = "Codi del Tipus de Login")
  public Integer getLoginType() {
    return loginType;
  }

  public void setLoginType(Integer loginType) {
    this.loginType = loginType;
  }

  public EvidenciaWs loginTypeDescription(String loginTypeDescription) {
    this.loginTypeDescription = loginTypeDescription;
    return this;
  }

   /**
   * Descripció del tipus de login
   * @return loginTypeDescription
  **/
  @Schema(required = true, description = "Descripció del tipus de login")
  public String getLoginTypeDescription() {
    return loginTypeDescription;
  }

  public void setLoginTypeDescription(String loginTypeDescription) {
    this.loginTypeDescription = loginTypeDescription;
  }

  public EvidenciaWs loginSubtype(String loginSubtype) {
    this.loginSubtype = loginSubtype;
    return this;
  }

   /**
   * Subtipus de login
   * @return loginSubtype
  **/
  @Schema(required = true, description = "Subtipus de login")
  public String getLoginSubtype() {
    return loginSubtype;
  }

  public void setLoginSubtype(String loginSubtype) {
    this.loginSubtype = loginSubtype;
  }

  public EvidenciaWs loginQaa(String loginQaa) {
    this.loginQaa = loginQaa;
    return this;
  }

   /**
   * Nivell des eguretat de login
   * @return loginQaa
  **/
  @Schema(required = true, description = "Nivell des eguretat de login")
  public String getLoginQaa() {
    return loginQaa;
  }

  public void setLoginQaa(String loginQaa) {
    this.loginQaa = loginQaa;
  }

  public EvidenciaWs loginData(DateTime loginData) {
    this.loginData = loginData;
    return this;
  }

   /**
   * Data de realització del login
   * @return loginData
  **/
  @Schema(required = true, description = "Data de realització del login")
  public DateTime getLoginData() {
    return loginData;
  }

  public void setLoginData(DateTime loginData) {
    this.loginData = loginData;
  }

  public EvidenciaWs loginId(String loginId) {
    this.loginId = loginId;
    return this;
  }

   /**
   * Identificador del login realitzat.
   * @return loginId
  **/
  @Schema(required = true, description = "Identificador del login realitzat.")
  public String getLoginId() {
    return loginId;
  }

  public void setLoginId(String loginId) {
    this.loginId = loginId;
  }

  public EvidenciaWs loginAuthMethod(String loginAuthMethod) {
    this.loginAuthMethod = loginAuthMethod;
    return this;
  }

   /**
   * Get loginAuthMethod
   * @return loginAuthMethod
  **/
  @Schema(description = "")
  public String getLoginAuthMethod() {
    return loginAuthMethod;
  }

  public void setLoginAuthMethod(String loginAuthMethod) {
    this.loginAuthMethod = loginAuthMethod;
  }

  public EvidenciaWs loginAdditionalProperties(String loginAdditionalProperties) {
    this.loginAdditionalProperties = loginAdditionalProperties;
    return this;
  }

   /**
   * Get loginAdditionalProperties
   * @return loginAdditionalProperties
  **/
  @Schema(description = "")
  public String getLoginAdditionalProperties() {
    return loginAdditionalProperties;
  }

  public void setLoginAdditionalProperties(String loginAdditionalProperties) {
    this.loginAdditionalProperties = loginAdditionalProperties;
  }

  public EvidenciaWs localitzacioIp(String localitzacioIp) {
    this.localitzacioIp = localitzacioIp;
    return this;
  }

   /**
   * IP des d&#x27;on està connectat el ciutadà
   * @return localitzacioIp
  **/
  @Schema(description = "IP des d'on està connectat el ciutadà")
  public String getLocalitzacioIp() {
    return localitzacioIp;
  }

  public void setLocalitzacioIp(String localitzacioIp) {
    this.localitzacioIp = localitzacioIp;
  }

  public EvidenciaWs localitzacioCodiPostal(String localitzacioCodiPostal) {
    this.localitzacioCodiPostal = localitzacioCodiPostal;
    return this;
  }

   /**
   * Codi postal des d&#x27;on està connectat el ciutadà.
   * @return localitzacioCodiPostal
  **/
  @Schema(description = "Codi postal des d'on està connectat el ciutadà.")
  public String getLocalitzacioCodiPostal() {
    return localitzacioCodiPostal;
  }

  public void setLocalitzacioCodiPostal(String localitzacioCodiPostal) {
    this.localitzacioCodiPostal = localitzacioCodiPostal;
  }

  public EvidenciaWs localitzacioLatitud(String localitzacioLatitud) {
    this.localitzacioLatitud = localitzacioLatitud;
    return this;
  }

   /**
   * Latitud des d&#x27;on està connectat el ciutadà.
   * @return localitzacioLatitud
  **/
  @Schema(description = "Latitud des d'on està connectat el ciutadà.")
  public String getLocalitzacioLatitud() {
    return localitzacioLatitud;
  }

  public void setLocalitzacioLatitud(String localitzacioLatitud) {
    this.localitzacioLatitud = localitzacioLatitud;
  }

  public EvidenciaWs localitzacioLongitud(String localitzacioLongitud) {
    this.localitzacioLongitud = localitzacioLongitud;
    return this;
  }

   /**
   * Longitud des d&#x27;on està connectat el ciutadà.
   * @return localitzacioLongitud
  **/
  @Schema(description = "Longitud des d'on està connectat el ciutadà.")
  public String getLocalitzacioLongitud() {
    return localitzacioLongitud;
  }

  public void setLocalitzacioLongitud(String localitzacioLongitud) {
    this.localitzacioLongitud = localitzacioLongitud;
  }

  public EvidenciaWs localitzacioCiutat(String localitzacioCiutat) {
    this.localitzacioCiutat = localitzacioCiutat;
    return this;
  }

   /**
   * Localitat des d&#x27;on està connectat el ciutadà.
   * @return localitzacioCiutat
  **/
  @Schema(description = "Localitat des d'on està connectat el ciutadà.")
  public String getLocalitzacioCiutat() {
    return localitzacioCiutat;
  }

  public void setLocalitzacioCiutat(String localitzacioCiutat) {
    this.localitzacioCiutat = localitzacioCiutat;
  }

  public EvidenciaWs localitzacioRegio(String localitzacioRegio) {
    this.localitzacioRegio = localitzacioRegio;
    return this;
  }

   /**
   * Regió (Si és Espanya Comunitat Autonoma) des d&#x27;on està connectat el ciutadà.
   * @return localitzacioRegio
  **/
  @Schema(description = "Regió (Si és Espanya Comunitat Autonoma) des d'on està connectat el ciutadà.")
  public String getLocalitzacioRegio() {
    return localitzacioRegio;
  }

  public void setLocalitzacioRegio(String localitzacioRegio) {
    this.localitzacioRegio = localitzacioRegio;
  }

  public EvidenciaWs localitzacioPais(String localitzacioPais) {
    this.localitzacioPais = localitzacioPais;
    return this;
  }

   /**
   * Pais des d&#x27;on està connectat el ciutadà.
   * @return localitzacioPais
  **/
  @Schema(description = "Pais des d'on està connectat el ciutadà.")
  public String getLocalitzacioPais() {
    return localitzacioPais;
  }

  public void setLocalitzacioPais(String localitzacioPais) {
    this.localitzacioPais = localitzacioPais;
  }

  public EvidenciaWs firmaReason(String firmaReason) {
    this.firmaReason = firmaReason;
    return this;
  }

   /**
   * Raó de firma.
   * @return firmaReason
  **/
  @Schema(required = true, description = "Raó de firma.")
  public String getFirmaReason() {
    return firmaReason;
  }

  public void setFirmaReason(String firmaReason) {
    this.firmaReason = firmaReason;
  }

  public EvidenciaWs firmaIdiomaDocument(String firmaIdiomaDocument) {
    this.firmaIdiomaDocument = firmaIdiomaDocument;
    return this;
  }

   /**
   * Idioma en que està escrit el document.
   * @return firmaIdiomaDocument
  **/
  @Schema(required = true, description = "Idioma en que està escrit el document.")
  public String getFirmaIdiomaDocument() {
    return firmaIdiomaDocument;
  }

  public void setFirmaIdiomaDocument(String firmaIdiomaDocument) {
    this.firmaIdiomaDocument = firmaIdiomaDocument;
  }

  public EvidenciaWs firmaTipusDocumental(Integer firmaTipusDocumental) {
    this.firmaTipusDocumental = firmaTipusDocumental;
    return this;
  }

   /**
   * Tipus documental de la Firma. Veure https://administracionelectronica.gob.es/pae_Home/dam/jcr:26d90313-7af0-4f69-9d62-c853d55d7627/Esquema_Metadatos_e-EMGDE_2016.pdf
   * @return firmaTipusDocumental
  **/
  @Schema(required = true, description = "Tipus documental de la Firma. Veure https://administracionelectronica.gob.es/pae_Home/dam/jcr:26d90313-7af0-4f69-9d62-c853d55d7627/Esquema_Metadatos_e-EMGDE_2016.pdf")
  public Integer getFirmaTipusDocumental() {
    return firmaTipusDocumental;
  }

  public void setFirmaTipusDocumental(Integer firmaTipusDocumental) {
    this.firmaTipusDocumental = firmaTipusDocumental;
  }

  public EvidenciaWs firmaTipusDocumentalDescripcio(String firmaTipusDocumentalDescripcio) {
    this.firmaTipusDocumentalDescripcio = firmaTipusDocumentalDescripcio;
    return this;
  }

   /**
   * DescripcioTipus documental de la Firma.Per exemple per 1 retorna &#x27;Resolución(TD01)&#x27;
   * @return firmaTipusDocumentalDescripcio
  **/
  @Schema(example = "1", required = true, description = "DescripcioTipus documental de la Firma.Per exemple per 1 retorna 'Resolución(TD01)'")
  public String getFirmaTipusDocumentalDescripcio() {
    return firmaTipusDocumentalDescripcio;
  }

  public void setFirmaTipusDocumentalDescripcio(String firmaTipusDocumentalDescripcio) {
    this.firmaTipusDocumentalDescripcio = firmaTipusDocumentalDescripcio;
  }

  public EvidenciaWs fitxerOriginal(EvidenciaFile fitxerOriginal) {
    this.fitxerOriginal = fitxerOriginal;
    return this;
  }

   /**
   * Get fitxerOriginal
   * @return fitxerOriginal
  **/
  @Schema(required = true, description = "")
  public EvidenciaFile getFitxerOriginal() {
    return fitxerOriginal;
  }

  public void setFitxerOriginal(EvidenciaFile fitxerOriginal) {
    this.fitxerOriginal = fitxerOriginal;
  }

  public EvidenciaWs fitxerAdaptat(EvidenciaFile fitxerAdaptat) {
    this.fitxerAdaptat = fitxerAdaptat;
    return this;
  }

   /**
   * Get fitxerAdaptat
   * @return fitxerAdaptat
  **/
  @Schema(description = "")
  public EvidenciaFile getFitxerAdaptat() {
    return fitxerAdaptat;
  }

  public void setFitxerAdaptat(EvidenciaFile fitxerAdaptat) {
    this.fitxerAdaptat = fitxerAdaptat;
  }

  public EvidenciaWs fitxerSignat(EvidenciaFile fitxerSignat) {
    this.fitxerSignat = fitxerSignat;
    return this;
  }

   /**
   * Get fitxerSignat
   * @return fitxerSignat
  **/
  @Schema(description = "")
  public EvidenciaFile getFitxerSignat() {
    return fitxerSignat;
  }

  public void setFitxerSignat(EvidenciaFile fitxerSignat) {
    this.fitxerSignat = fitxerSignat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvidenciaWs evidenciaWs = (EvidenciaWs) o;
    return Objects.equals(this.evidenciaID, evidenciaWs.evidenciaID) &&
        Objects.equals(this.nom, evidenciaWs.nom) &&
        Objects.equals(this.personaNom, evidenciaWs.personaNom) &&
        Objects.equals(this.personaLlinatge1, evidenciaWs.personaLlinatge1) &&
        Objects.equals(this.personaLlinatge2, evidenciaWs.personaLlinatge2) &&
        Objects.equals(this.personaNif, evidenciaWs.personaNif) &&
        Objects.equals(this.personaEmail, evidenciaWs.personaEmail) &&
        Objects.equals(this.personaMobil, evidenciaWs.personaMobil) &&
        Objects.equals(this.dataInici, evidenciaWs.dataInici) &&
        Objects.equals(this.dataFi, evidenciaWs.dataFi) &&
        Objects.equals(this.estatCodi, evidenciaWs.estatCodi) &&
        Objects.equals(this.estatCodiDescripcio, evidenciaWs.estatCodiDescripcio) &&
        Objects.equals(this.estatError, evidenciaWs.estatError) &&
        Objects.equals(this.estatExcepcio, evidenciaWs.estatExcepcio) &&
        Objects.equals(this.loginType, evidenciaWs.loginType) &&
        Objects.equals(this.loginTypeDescription, evidenciaWs.loginTypeDescription) &&
        Objects.equals(this.loginSubtype, evidenciaWs.loginSubtype) &&
        Objects.equals(this.loginQaa, evidenciaWs.loginQaa) &&
        Objects.equals(this.loginData, evidenciaWs.loginData) &&
        Objects.equals(this.loginId, evidenciaWs.loginId) &&
        Objects.equals(this.loginAuthMethod, evidenciaWs.loginAuthMethod) &&
        Objects.equals(this.loginAdditionalProperties, evidenciaWs.loginAdditionalProperties) &&
        Objects.equals(this.localitzacioIp, evidenciaWs.localitzacioIp) &&
        Objects.equals(this.localitzacioCodiPostal, evidenciaWs.localitzacioCodiPostal) &&
        Objects.equals(this.localitzacioLatitud, evidenciaWs.localitzacioLatitud) &&
        Objects.equals(this.localitzacioLongitud, evidenciaWs.localitzacioLongitud) &&
        Objects.equals(this.localitzacioCiutat, evidenciaWs.localitzacioCiutat) &&
        Objects.equals(this.localitzacioRegio, evidenciaWs.localitzacioRegio) &&
        Objects.equals(this.localitzacioPais, evidenciaWs.localitzacioPais) &&
        Objects.equals(this.firmaReason, evidenciaWs.firmaReason) &&
        Objects.equals(this.firmaIdiomaDocument, evidenciaWs.firmaIdiomaDocument) &&
        Objects.equals(this.firmaTipusDocumental, evidenciaWs.firmaTipusDocumental) &&
        Objects.equals(this.firmaTipusDocumentalDescripcio, evidenciaWs.firmaTipusDocumentalDescripcio) &&
        Objects.equals(this.fitxerOriginal, evidenciaWs.fitxerOriginal) &&
        Objects.equals(this.fitxerAdaptat, evidenciaWs.fitxerAdaptat) &&
        Objects.equals(this.fitxerSignat, evidenciaWs.fitxerSignat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(evidenciaID, nom, personaNom, personaLlinatge1, personaLlinatge2, personaNif, personaEmail, personaMobil, dataInici, dataFi, estatCodi, estatCodiDescripcio, estatError, estatExcepcio, loginType, loginTypeDescription, loginSubtype, loginQaa, loginData, loginId, loginAuthMethod, loginAdditionalProperties, localitzacioIp, localitzacioCodiPostal, localitzacioLatitud, localitzacioLongitud, localitzacioCiutat, localitzacioRegio, localitzacioPais, firmaReason, firmaIdiomaDocument, firmaTipusDocumental, firmaTipusDocumentalDescripcio, fitxerOriginal, fitxerAdaptat, fitxerSignat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvidenciaWs {\n");
    
    sb.append("    evidenciaID: ").append(toIndentedString(evidenciaID)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    personaNom: ").append(toIndentedString(personaNom)).append("\n");
    sb.append("    personaLlinatge1: ").append(toIndentedString(personaLlinatge1)).append("\n");
    sb.append("    personaLlinatge2: ").append(toIndentedString(personaLlinatge2)).append("\n");
    sb.append("    personaNif: ").append(toIndentedString(personaNif)).append("\n");
    sb.append("    personaEmail: ").append(toIndentedString(personaEmail)).append("\n");
    sb.append("    personaMobil: ").append(toIndentedString(personaMobil)).append("\n");
    sb.append("    dataInici: ").append(toIndentedString(dataInici)).append("\n");
    sb.append("    dataFi: ").append(toIndentedString(dataFi)).append("\n");
    sb.append("    estatCodi: ").append(toIndentedString(estatCodi)).append("\n");
    sb.append("    estatCodiDescripcio: ").append(toIndentedString(estatCodiDescripcio)).append("\n");
    sb.append("    estatError: ").append(toIndentedString(estatError)).append("\n");
    sb.append("    estatExcepcio: ").append(toIndentedString(estatExcepcio)).append("\n");
    sb.append("    loginType: ").append(toIndentedString(loginType)).append("\n");
    sb.append("    loginTypeDescription: ").append(toIndentedString(loginTypeDescription)).append("\n");
    sb.append("    loginSubtype: ").append(toIndentedString(loginSubtype)).append("\n");
    sb.append("    loginQaa: ").append(toIndentedString(loginQaa)).append("\n");
    sb.append("    loginData: ").append(toIndentedString(loginData)).append("\n");
    sb.append("    loginId: ").append(toIndentedString(loginId)).append("\n");
    sb.append("    loginAuthMethod: ").append(toIndentedString(loginAuthMethod)).append("\n");
    sb.append("    loginAdditionalProperties: ").append(toIndentedString(loginAdditionalProperties)).append("\n");
    sb.append("    localitzacioIp: ").append(toIndentedString(localitzacioIp)).append("\n");
    sb.append("    localitzacioCodiPostal: ").append(toIndentedString(localitzacioCodiPostal)).append("\n");
    sb.append("    localitzacioLatitud: ").append(toIndentedString(localitzacioLatitud)).append("\n");
    sb.append("    localitzacioLongitud: ").append(toIndentedString(localitzacioLongitud)).append("\n");
    sb.append("    localitzacioCiutat: ").append(toIndentedString(localitzacioCiutat)).append("\n");
    sb.append("    localitzacioRegio: ").append(toIndentedString(localitzacioRegio)).append("\n");
    sb.append("    localitzacioPais: ").append(toIndentedString(localitzacioPais)).append("\n");
    sb.append("    firmaReason: ").append(toIndentedString(firmaReason)).append("\n");
    sb.append("    firmaIdiomaDocument: ").append(toIndentedString(firmaIdiomaDocument)).append("\n");
    sb.append("    firmaTipusDocumental: ").append(toIndentedString(firmaTipusDocumental)).append("\n");
    sb.append("    firmaTipusDocumentalDescripcio: ").append(toIndentedString(firmaTipusDocumentalDescripcio)).append("\n");
    sb.append("    fitxerOriginal: ").append(toIndentedString(fitxerOriginal)).append("\n");
    sb.append("    fitxerAdaptat: ").append(toIndentedString(fitxerAdaptat)).append("\n");
    sb.append("    fitxerSignat: ").append(toIndentedString(fitxerSignat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
