/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.evidenciesib.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Fitxer
 */


public class Fitxer {
  @JsonProperty("descripcio")
  private String descripcio = null;

  @JsonProperty("mime")
  private String mime = null;

  @JsonProperty("nom")
  private String nom = null;

  @JsonProperty("encryptedFileID")
  private String encryptedFileID = null;

  @JsonProperty("fitxerID")
  private Long fitxerID = null;

  @JsonProperty("tamany")
  private Long tamany = null;

  public Fitxer descripcio(String descripcio) {
    this.descripcio = descripcio;
    return this;
  }

   /**
   * Get descripcio
   * @return descripcio
  **/
  @Schema(description = "")
  public String getDescripcio() {
    return descripcio;
  }

  public void setDescripcio(String descripcio) {
    this.descripcio = descripcio;
  }

  public Fitxer mime(String mime) {
    this.mime = mime;
    return this;
  }

   /**
   * Get mime
   * @return mime
  **/
  @Schema(description = "")
  public String getMime() {
    return mime;
  }

  public void setMime(String mime) {
    this.mime = mime;
  }

  public Fitxer nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Get nom
   * @return nom
  **/
  @Schema(description = "")
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }

  public Fitxer encryptedFileID(String encryptedFileID) {
    this.encryptedFileID = encryptedFileID;
    return this;
  }

   /**
   * Get encryptedFileID
   * @return encryptedFileID
  **/
  @Schema(description = "")
  public String getEncryptedFileID() {
    return encryptedFileID;
  }

  public void setEncryptedFileID(String encryptedFileID) {
    this.encryptedFileID = encryptedFileID;
  }

  public Fitxer fitxerID(Long fitxerID) {
    this.fitxerID = fitxerID;
    return this;
  }

   /**
   * Get fitxerID
   * @return fitxerID
  **/
  @Schema(description = "")
  public Long getFitxerID() {
    return fitxerID;
  }

  public void setFitxerID(Long fitxerID) {
    this.fitxerID = fitxerID;
  }

  public Fitxer tamany(Long tamany) {
    this.tamany = tamany;
    return this;
  }

   /**
   * Get tamany
   * @return tamany
  **/
  @Schema(description = "")
  public Long getTamany() {
    return tamany;
  }

  public void setTamany(Long tamany) {
    this.tamany = tamany;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fitxer fitxer = (Fitxer) o;
    return Objects.equals(this.descripcio, fitxer.descripcio) &&
        Objects.equals(this.mime, fitxer.mime) &&
        Objects.equals(this.nom, fitxer.nom) &&
        Objects.equals(this.encryptedFileID, fitxer.encryptedFileID) &&
        Objects.equals(this.fitxerID, fitxer.fitxerID) &&
        Objects.equals(this.tamany, fitxer.tamany);
  }

  @Override
  public int hashCode() {
    return Objects.hash(descripcio, mime, nom, encryptedFileID, fitxerID, tamany);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fitxer {\n");
    
    sb.append("    descripcio: ").append(toIndentedString(descripcio)).append("\n");
    sb.append("    mime: ").append(toIndentedString(mime)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    encryptedFileID: ").append(toIndentedString(encryptedFileID)).append("\n");
    sb.append("    fitxerID: ").append(toIndentedString(fitxerID)).append("\n");
    sb.append("    tamany: ").append(toIndentedString(tamany)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
