<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>evidenciesib-ejb</artifactId>
    <packaging>ejb</packaging>

    <parent>
        <groupId>es.caib.evidenciesib</groupId>
        <artifactId>evidenciesib</artifactId>
        <version>1.0.9</version>
    </parent>

    <name>EvidenciesIB - EJB</name>

    <dependencies>

        <dependency>
            <groupId>es.caib.evidenciesib</groupId>
            <artifactId>evidenciesib-persistence</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>es.caib.evidenciesib</groupId>
            <artifactId>evidenciesib-commons</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <artifactId>pluginsib-userinformation-api</artifactId>
            <groupId>org.fundaciobit.pluginsib.userinformation</groupId>
            <version>${pluginsib.userinformation.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.utils</groupId>
            <artifactId>pluginsib-utils-templateengine</artifactId>
            <version>${pluginsib.utils.version}</version>
        </dependency>

        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itextpdf</artifactId>
            <version>5.4.3</version>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>

        <dependency>
            <artifactId>apifirmasimple-jersey</artifactId>
            <groupId>org.fundaciobit.apisib.apifirmasimple</groupId>
            <version>1.0.3</version>
            <exclusions>
                <exclusion>
                    <artifactId>log4j</artifactId>
                    <groupId>log4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- UtilitatsFirma - API Rest - Interna Client - Utilitats de Firma v2 -->
        <dependency>
            <groupId>es.caib.utilitatsfirma</groupId>
            <artifactId>utilitatsfirma-api-interna-client-utilitatsfirma-v2</artifactId>
            <version>2.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <artifactId>jsr305</artifactId>
                    <groupId>com.google.code.findbugs</groupId>
                </exclusion>
            </exclusions>
        </dependency>


        <dependency>
            <artifactId>pluginsib-login-api</artifactId>
            <groupId>org.fundaciobit.pluginsib.login</groupId>
            <version>${pluginsib.login.version}</version>
        </dependency>


    </dependencies>

    <build>
        <finalName>${project.artifactId}-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ejb-plugin</artifactId>
                <configuration>
                    <ejbVersion>3.2</ejbVersion>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>