

# Dialecte de Hibernate
es.caib.evidenciesib.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# es.caib.evidenciesib.hibernate.dialect=org.hibernate.dialect.MySQLDialect      
# es.caib.evidenciesib.hibernate.dialect=org.hibernate.dialect.DB2Dialect
# es.caib.evidenciesib.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# es.caib.evidenciesib.hibernate.dialect=net.sf.hibernate.dialect.Oracle9Dialect

# es.caib.evidenciesib.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
# es.caib.evidenciesib.hibernate.query.substitutions=true 1, false 0
es.caib.evidenciesib.hibernate.show_sql=false
es.caib.evidenciesib.hibernate.format_sql=false


# Propietat que indica als projectes que activin les caracteristiques
# especials requerides en l'entorn de la CAIB (Govern Balear) si val true -->
es.caib.evidenciesib.iscaib=false


es.caib.evidenciesib.defaultlanguage=ca

es.caib.evidenciesib.development=false

#  Clau per encriptar l'identificador del fitxers a descarregar via web(IMPORTANT tamany de 16 caràcters) -->
es.caib.evidenciesib.encryptkey=1234567890123456

#  Llistat de Plugins per l'exportació de dades en els llistats (excel, ods, csv, ...) -->
# es.caib.evidenciesib.exportdataplugins=org.fundaciobit.plugins.exportdata.cvs.CSVPlugin,org.fundaciobit.plugins.exportdata.ods.ODSPlugin,org.fundaciobit.plugins.exportdata.excel.ExcelPlugin

# From per quan enviam correus
es.caib.evidenciesib.email.from=evidenciesib@evidenciesib.org

# URLs
es.caib.evidenciesib.url.back=http://localhost:8080/evidenciesibback
es.caib.evidenciesib.url.front=http://localhost:8080/evidenciesibfront


# Configuració de la Web UI

# Opcional. Canvia el color de la barra superior. Format HTML. Exemple #FF0000
#es.caib.evidenciesib.webui.headercolor=#FF0000
# Opcional. Canvia el logo de la barra superior. Format URL.
#es.caib.evidenciesib.webui.headerlogourl=https://
# Opcional. Canvia el logo de la barra inferior. Format URL.
#es.caib.evidenciesib.webui.footerlogourl=https://

# Pop up d'ajuda del Back
es.caib.evidenciesib.back.help.url=https://suport.caib.es
es.caib.evidenciesib.back.help.email=suport@caib.es
es.caib.evidenciesib.back.help.telefon=77070

#-----------------------------------------
# Configuració de la Capçalera del FRONT
# ----------------------------------------

# Opcional. Valor per defecte false. Nou a la versió 1.0.5. En les pantalles de 
# firma del front posa una capçalera si aquesta propietat val true.
es.caib.evidenciesib.front.signatureheader.enabled=false

# Opcional. Nou a la versió 1.0.5. Valor per defecte és el color del back. 
# En cas que aquesta propietat tampoc estigui definida llavors 
# s’utilitzarà #2E8B57. En la pantalla de selecció del mòdul de firma posa una
# capçalera amb color de fons definit per aquesta propietat. Només es mostrarà
# la capçalera si la propietat es.caib.evidenciesib.front.signatureheader.enabled val true
es.caib.evidenciesib.front.signatureheader.backgroundcolor=#FF0000

# Opcional. Nou a la versió 1.0.5. Valor per defecte el logo de la capçalera del back.
# En la pantalla de selecció del mòdul de firma posa una capçalera amb un logo
# definit per aquesta propietat. Només es mostrarà la capçalera si la propietat
# es.caib.evidenciesib.front.signatureheader.enabled val true
es.caib.evidenciesib.front.signatureheader.logourl=http://anadal:8080/portafibback/common/arxiu/GH9NHmWp8uCwY0UbhAy48Q==?nom=fundaciobit-logo-peu.png&mime=image%2Fpng
        
# Opcional. Nou a la versió 1.0.5. Per defecte és el nom de l´entitat. En la pantalla de
# selecció del mòdul de firma posa una capçalera amb un text definit per aquesta
# propietat. Si no està definida, el valor per defecte és selecciona «EvidènciesIB».
# Si val "-" llavors significa que no es vol mostrar cap text. Només es mostrarà
# la capçalera si la propietat es.caib.evidenciesib.front.signatureheader.enabled val true
es.caib.evidenciesib.front.signatureheader.text=MY ENTITY