

# Dialecte de Hibernate
es.caib.evidenciesib.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# es.caib.evidenciesib.hibernate.dialect=org.hibernate.dialect.MySQLDialect      
# es.caib.evidenciesib.hibernate.dialect=org.hibernate.dialect.DB2Dialect
# es.caib.evidenciesib.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# es.caib.evidenciesib.hibernate.dialect=net.sf.hibernate.dialect.Oracle9Dialect

# es.caib.evidenciesib.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
# es.caib.evidenciesib.hibernate.query.substitutions=true 1, false 0
es.caib.evidenciesib.hibernate.show_sql=false
es.caib.evidenciesib.hibernate.format_sql=false


# Propietat que indica als projectes que activin les caracteristiques
# especials requerides en l'entorn de la CAIB (Govern Balear) si val true -->
es.caib.evidenciesib.iscaib=false


es.caib.evidenciesib.defaultlanguage=ca

es.caib.evidenciesib.development=false

#  Clau per encriptar l'identificador del fitxers a descarregar via web(IMPORTANT tamany de 16 caràcters) -->
es.caib.evidenciesib.encryptkey=1234567890123456

#  Llistat de Plugins per l'exportació de dades en els llistats (excel, ods, csv, ...) -->
# es.caib.evidenciesib.exportdataplugins=org.fundaciobit.plugins.exportdata.cvs.CSVPlugin,org.fundaciobit.plugins.exportdata.ods.ODSPlugin,org.fundaciobit.plugins.exportdata.excel.ExcelPlugin

# From per quan enviam correus
es.caib.evidenciesib.email.from=evidenciesib@evidenciesib.org

# URLs
es.caib.evidenciesib.url.back=http://localhost:8080/evidenciesibback
es.caib.evidenciesib.url.front=http://localhost:8080/evidenciesibfront


# Configuració de la Web UI

# Opcional. Canvia el color de la barra superior. Format HTML. Exemple #FF0000
#es.caib.evidenciesib.webui.headercolor=#FF0000
# Opcional. Canvia el logo de la barra superior. Format URL.
#es.caib.evidenciesib.webui.headerlogourl=https://
# Opcional. Canvia el logo de la barra inferior. Format URL.
#es.caib.evidenciesib.webui.footerlogourl=https://

# Pop up d'ajuda del Back
es.caib.evidenciesib.back.help.url=https://suport.caib.es
es.caib.evidenciesib.back.help.email=suport@caib.es
es.caib.evidenciesib.back.help.telefon=77070
