/*
 * API REST INTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'interior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.evidenciesib.apiinterna.client.api;

import es.caib.evidenciesib.apiinterna.client.services.ApiException;
import es.caib.evidenciesib.apiinterna.client.model.SendMessageResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NotificacionsApi
 */
@Ignore
public class NotificacionsApiTest {

    private final NotificacionsApi api = new NotificacionsApi();

    /**
     * Envia un missatge al mòbil del ciutada a traves de l&#x27;App de Carpeta.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendNotificationToMobileTest() throws ApiException {
        List<String> notificationParameters = null;
        String langError = null;
        SendMessageResult response = api.sendNotificationToMobile(notificationParameters, langError);

        // TODO: test validations
    }
}
