/*
 * API REST INTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'interior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.evidenciesib.apiinterna.client.api;

import es.caib.evidenciesib.apiinterna.client.services.ApiException;
import es.caib.evidenciesib.apiinterna.client.model.ExamplePojo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VersiApi
 */
@Ignore
public class VersiApiTest {

    private final VersiApi api = new VersiApi();

    /**
     * Versio de l&#x27;Aplicació
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versioTest() throws ApiException {
        String idioma = null;
        ExamplePojo response = api.versio(idioma);

        // TODO: test validations
    }
}
