/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.apiexterna.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConstantsWs
 */
public class ConstantsWsTest {
    private final ConstantsWs model = new ConstantsWs();

    /**
     * Model tests for ConstantsWs
     */
    @Test
    public void testConstantsWs() {
        // TODO: test ConstantsWs
    }

    /**
     * Test the property 'EVIDENCIA_ESTAT_CODI_ERROR'
     */
    @Test
    public void EVIDENCIA_ESTAT_CODI_ERRORTest() {
        // TODO: test EVIDENCIA_ESTAT_CODI_ERROR
    }

    /**
     * Test the property 'EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO'
     */
    @Test
    public void EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIOTest() {
        // TODO: test EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO
    }

    /**
     * Test the property 'EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN'
     */
    @Test
    public void EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGINTest() {
        // TODO: test EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN
    }

    /**
     * Test the property 'EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA'
     */
    @Test
    public void EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMATest() {
        // TODO: test EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA
    }

    /**
     * Test the property 'EVIDENCIA_ESTAT_CODI_SIGNAT'
     */
    @Test
    public void EVIDENCIA_ESTAT_CODI_SIGNATTest() {
        // TODO: test EVIDENCIA_ESTAT_CODI_SIGNAT
    }

}
