/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.apiexterna.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.evidenciesib.apiexterna.client.model.EvidenciaWs;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EvidenciaWsPaginacio
 */
public class EvidenciaWsPaginacioTest {
    private final EvidenciaWsPaginacio model = new EvidenciaWsPaginacio();

    /**
     * Model tests for EvidenciaWsPaginacio
     */
    @Test
    public void testEvidenciaWsPaginacio() {
        // TODO: test EvidenciaWsPaginacio
    }

    /**
     * Test the property 'pagesize'
     */
    @Test
    public void pagesizeTest() {
        // TODO: test pagesize
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'totalpages'
     */
    @Test
    public void totalpagesTest() {
        // TODO: test totalpages
    }

    /**
     * Test the property 'totalcount'
     */
    @Test
    public void totalcountTest() {
        // TODO: test totalcount
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
