/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.apiexterna.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EvidenciaFileBase64
 */
public class EvidenciaFileBase64Test {
    private final EvidenciaFileBase64 model = new EvidenciaFileBase64();

    /**
     * Model tests for EvidenciaFileBase64
     */
    @Test
    public void testEvidenciaFileBase64() {
        // TODO: test EvidenciaFileBase64
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'mime'
     */
    @Test
    public void mimeTest() {
        // TODO: test mime
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'encryptedFileID'
     */
    @Test
    public void encryptedFileIDTest() {
        // TODO: test encryptedFileID
    }

    /**
     * Test the property 'documentBase64'
     */
    @Test
    public void documentBase64Test() {
        // TODO: test documentBase64
    }

}
