/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.apiexterna.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EvidenciaStartResponse
 */
public class EvidenciaStartResponseTest {
    private final EvidenciaStartResponse model = new EvidenciaStartResponse();

    /**
     * Model tests for EvidenciaStartResponse
     */
    @Test
    public void testEvidenciaStartResponse() {
        // TODO: test EvidenciaStartResponse
    }

    /**
     * Test the property 'evidenciaID'
     */
    @Test
    public void evidenciaIDTest() {
        // TODO: test evidenciaID
    }

    /**
     * Test the property 'evidenciaUrlRedirect'
     */
    @Test
    public void evidenciaUrlRedirectTest() {
        // TODO: test evidenciaUrlRedirect
    }

}
