/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.apiexterna.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.evidenciesib.apiexterna.client.model.EvidenciaFile;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EvidenciaWs
 */
public class EvidenciaWsTest {
    private final EvidenciaWs model = new EvidenciaWs();

    /**
     * Model tests for EvidenciaWs
     */
    @Test
    public void testEvidenciaWs() {
        // TODO: test EvidenciaWs
    }

    /**
     * Test the property 'evidenciaID'
     */
    @Test
    public void evidenciaIDTest() {
        // TODO: test evidenciaID
    }

    /**
     * Test the property 'nom'
     */
    @Test
    public void nomTest() {
        // TODO: test nom
    }

    /**
     * Test the property 'personaNom'
     */
    @Test
    public void personaNomTest() {
        // TODO: test personaNom
    }

    /**
     * Test the property 'personaLlinatge1'
     */
    @Test
    public void personaLlinatge1Test() {
        // TODO: test personaLlinatge1
    }

    /**
     * Test the property 'personaLlinatge2'
     */
    @Test
    public void personaLlinatge2Test() {
        // TODO: test personaLlinatge2
    }

    /**
     * Test the property 'personaNif'
     */
    @Test
    public void personaNifTest() {
        // TODO: test personaNif
    }

    /**
     * Test the property 'personaEmail'
     */
    @Test
    public void personaEmailTest() {
        // TODO: test personaEmail
    }

    /**
     * Test the property 'personaMobil'
     */
    @Test
    public void personaMobilTest() {
        // TODO: test personaMobil
    }

    /**
     * Test the property 'dataInici'
     */
    @Test
    public void dataIniciTest() {
        // TODO: test dataInici
    }

    /**
     * Test the property 'dataFi'
     */
    @Test
    public void dataFiTest() {
        // TODO: test dataFi
    }

    /**
     * Test the property 'estatCodi'
     */
    @Test
    public void estatCodiTest() {
        // TODO: test estatCodi
    }

    /**
     * Test the property 'estatCodiDescripcio'
     */
    @Test
    public void estatCodiDescripcioTest() {
        // TODO: test estatCodiDescripcio
    }

    /**
     * Test the property 'estatError'
     */
    @Test
    public void estatErrorTest() {
        // TODO: test estatError
    }

    /**
     * Test the property 'estatExcepcio'
     */
    @Test
    public void estatExcepcioTest() {
        // TODO: test estatExcepcio
    }

    /**
     * Test the property 'loginType'
     */
    @Test
    public void loginTypeTest() {
        // TODO: test loginType
    }

    /**
     * Test the property 'loginTypeDescription'
     */
    @Test
    public void loginTypeDescriptionTest() {
        // TODO: test loginTypeDescription
    }

    /**
     * Test the property 'loginSubtype'
     */
    @Test
    public void loginSubtypeTest() {
        // TODO: test loginSubtype
    }

    /**
     * Test the property 'loginQaa'
     */
    @Test
    public void loginQaaTest() {
        // TODO: test loginQaa
    }

    /**
     * Test the property 'loginData'
     */
    @Test
    public void loginDataTest() {
        // TODO: test loginData
    }

    /**
     * Test the property 'loginId'
     */
    @Test
    public void loginIdTest() {
        // TODO: test loginId
    }

    /**
     * Test the property 'loginAuthMethod'
     */
    @Test
    public void loginAuthMethodTest() {
        // TODO: test loginAuthMethod
    }

    /**
     * Test the property 'loginAdditionalProperties'
     */
    @Test
    public void loginAdditionalPropertiesTest() {
        // TODO: test loginAdditionalProperties
    }

    /**
     * Test the property 'localitzacioIp'
     */
    @Test
    public void localitzacioIpTest() {
        // TODO: test localitzacioIp
    }

    /**
     * Test the property 'localitzacioCodiPostal'
     */
    @Test
    public void localitzacioCodiPostalTest() {
        // TODO: test localitzacioCodiPostal
    }

    /**
     * Test the property 'localitzacioLatitud'
     */
    @Test
    public void localitzacioLatitudTest() {
        // TODO: test localitzacioLatitud
    }

    /**
     * Test the property 'localitzacioLongitud'
     */
    @Test
    public void localitzacioLongitudTest() {
        // TODO: test localitzacioLongitud
    }

    /**
     * Test the property 'localitzacioCiutat'
     */
    @Test
    public void localitzacioCiutatTest() {
        // TODO: test localitzacioCiutat
    }

    /**
     * Test the property 'localitzacioRegio'
     */
    @Test
    public void localitzacioRegioTest() {
        // TODO: test localitzacioRegio
    }

    /**
     * Test the property 'localitzacioPais'
     */
    @Test
    public void localitzacioPaisTest() {
        // TODO: test localitzacioPais
    }

    /**
     * Test the property 'firmaReason'
     */
    @Test
    public void firmaReasonTest() {
        // TODO: test firmaReason
    }

    /**
     * Test the property 'firmaIdiomaDocument'
     */
    @Test
    public void firmaIdiomaDocumentTest() {
        // TODO: test firmaIdiomaDocument
    }

    /**
     * Test the property 'firmaTipusDocumental'
     */
    @Test
    public void firmaTipusDocumentalTest() {
        // TODO: test firmaTipusDocumental
    }

    /**
     * Test the property 'firmaTipusDocumentalDescripcio'
     */
    @Test
    public void firmaTipusDocumentalDescripcioTest() {
        // TODO: test firmaTipusDocumentalDescripcio
    }

    /**
     * Test the property 'fitxerOriginal'
     */
    @Test
    public void fitxerOriginalTest() {
        // TODO: test fitxerOriginal
    }

    /**
     * Test the property 'fitxerAdaptat'
     */
    @Test
    public void fitxerAdaptatTest() {
        // TODO: test fitxerAdaptat
    }

    /**
     * Test the property 'fitxerSignat'
     */
    @Test
    public void fitxerSignatTest() {
        // TODO: test fitxerSignat
    }

}
