/*
 * API REST EXTERNA de EvidenciesIB
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: governdigital@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.apiexterna.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.evidenciesib.apiexterna.client.model.EvidenciaFile;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EvidenciaStartRequest
 */
public class EvidenciaStartRequestTest {
    private final EvidenciaStartRequest model = new EvidenciaStartRequest();

    /**
     * Model tests for EvidenciaStartRequest
     */
    @Test
    public void testEvidenciaStartRequest() {
        // TODO: test EvidenciaStartRequest
    }

    /**
     * Test the property 'titolEvidencia'
     */
    @Test
    public void titolEvidenciaTest() {
        // TODO: test titolEvidencia
    }

    /**
     * Test the property 'personaNom'
     */
    @Test
    public void personaNomTest() {
        // TODO: test personaNom
    }

    /**
     * Test the property 'personaLlinatge1'
     */
    @Test
    public void personaLlinatge1Test() {
        // TODO: test personaLlinatge1
    }

    /**
     * Test the property 'personaLlinatge2'
     */
    @Test
    public void personaLlinatge2Test() {
        // TODO: test personaLlinatge2
    }

    /**
     * Test the property 'personaNif'
     */
    @Test
    public void personaNifTest() {
        // TODO: test personaNif
    }

    /**
     * Test the property 'personaEmail'
     */
    @Test
    public void personaEmailTest() {
        // TODO: test personaEmail
    }

    /**
     * Test the property 'personaMobil'
     */
    @Test
    public void personaMobilTest() {
        // TODO: test personaMobil
    }

    /**
     * Test the property 'raoDeLaFirma'
     */
    @Test
    public void raoDeLaFirmaTest() {
        // TODO: test raoDeLaFirma
    }

    /**
     * Test the property 'languageDocument'
     */
    @Test
    public void languageDocumentTest() {
        // TODO: test languageDocument
    }

    /**
     * Test the property 'documentASignar'
     */
    @Test
    public void documentASignarTest() {
        // TODO: test documentASignar
    }

    /**
     * Test the property 'callBackUrl'
     */
    @Test
    public void callBackUrlTest() {
        // TODO: test callBackUrl
    }

    /**
     * Test the property 'languageUI'
     */
    @Test
    public void languageUITest() {
        // TODO: test languageUI
    }

}
