/*
 * API REST EXTERNA de EvidenciesIB - Evidencies
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.api.externa.client.evidencies.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Valors: • EVIDENCIA_ESTAT_CODI_ERROR&#x3D;-1(Codi d&#39;estat d&#39;una evidència que indica un error) • EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO&#x3D;1(Codi d&#39;estat d&#39;una evidència que indica que esta en procés de creació) • EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN&#x3D;2(Codi d&#39;estat d&#39;una evidència que indica que esta realitzant el login) • EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA&#x3D;3(Codi d&#39;estat d&#39;una evidència que indica que esta realitzant la firma del document) • EVIDENCIA_ESTAT_CODI_SIGNAT&#x3D;10(Codi d&#39;estat d&#39;una evidència que indica que ha finalitzat correctament)
 */
public enum EvidenciaStatus {
  
  /**
   * Codi d&#39;estat d&#39;una evidència que indica un error
   */
  EVIDENCIA_ESTAT_CODI_ERROR(-1),
  
  /**
   * Codi d&#39;estat d&#39;una evidència que indica que esta en procés de creació
   */
  EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO(1),
  
  /**
   * Codi d&#39;estat d&#39;una evidència que indica que esta realitzant el login
   */
  EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN(2),
  
  /**
   * Codi d&#39;estat d&#39;una evidència que indica que esta realitzant la firma del document
   */
  EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA(3),
  
  /**
   * Codi d&#39;estat d&#39;una evidència que indica que ha finalitzat correctament
   */
  EVIDENCIA_ESTAT_CODI_SIGNAT(10);

  private Integer value;

  EvidenciaStatus(Integer value) {
    this.value = value;
  }

  @JsonValue
  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static EvidenciaStatus fromValue(Integer value) {
    for (EvidenciaStatus b : EvidenciaStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

