/*
 * API REST EXTERNA de EvidenciesIB - Evidencies
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.api.externa.client.evidencies.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.evidenciesib.api.externa.client.evidencies.v1.model.EvidenciaWs;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EvidenciaWsPaginacio
 */
@JsonPropertyOrder({
  EvidenciaWsPaginacio.JSON_PROPERTY_PAGE,
  EvidenciaWsPaginacio.JSON_PROPERTY_PAGESIZE,
  EvidenciaWsPaginacio.JSON_PROPERTY_TOTALPAGES,
  EvidenciaWsPaginacio.JSON_PROPERTY_TOTALCOUNT,
  EvidenciaWsPaginacio.JSON_PROPERTY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class EvidenciaWsPaginacio {
  public static final String JSON_PROPERTY_PAGE = "page";
  @javax.annotation.Nonnull
  private Integer page;

  public static final String JSON_PROPERTY_PAGESIZE = "pagesize";
  @javax.annotation.Nonnull
  private Integer pagesize;

  public static final String JSON_PROPERTY_TOTALPAGES = "totalpages";
  @javax.annotation.Nonnull
  private Integer totalpages;

  public static final String JSON_PROPERTY_TOTALCOUNT = "totalcount";
  @javax.annotation.Nonnull
  private Integer totalcount;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nonnull
  private List<EvidenciaWs> data = new ArrayList<>();

  public EvidenciaWsPaginacio() {
  }

  public EvidenciaWsPaginacio page(@javax.annotation.Nonnull Integer page) {
    
    this.page = page;
    return this;
  }

  /**
   * Número pàgina. Comença per 1.
   * @return page
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getPage() {
    return page;
  }


  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPage(@javax.annotation.Nonnull Integer page) {
    this.page = page;
  }

  public EvidenciaWsPaginacio pagesize(@javax.annotation.Nonnull Integer pagesize) {
    
    this.pagesize = pagesize;
    return this;
  }

  /**
   * Mida de pàgina
   * @return pagesize
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAGESIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getPagesize() {
    return pagesize;
  }


  @JsonProperty(JSON_PROPERTY_PAGESIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPagesize(@javax.annotation.Nonnull Integer pagesize) {
    this.pagesize = pagesize;
  }

  public EvidenciaWsPaginacio totalpages(@javax.annotation.Nonnull Integer totalpages) {
    
    this.totalpages = totalpages;
    return this;
  }

  /**
   * Número total de pàgines
   * @return totalpages
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOTALPAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTotalpages() {
    return totalpages;
  }


  @JsonProperty(JSON_PROPERTY_TOTALPAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalpages(@javax.annotation.Nonnull Integer totalpages) {
    this.totalpages = totalpages;
  }

  public EvidenciaWsPaginacio totalcount(@javax.annotation.Nonnull Integer totalcount) {
    
    this.totalcount = totalcount;
    return this;
  }

  /**
   * Numero total d&#39;elements
   * @return totalcount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOTALCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTotalcount() {
    return totalcount;
  }


  @JsonProperty(JSON_PROPERTY_TOTALCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalcount(@javax.annotation.Nonnull Integer totalcount) {
    this.totalcount = totalcount;
  }

  public EvidenciaWsPaginacio data(@javax.annotation.Nonnull List<EvidenciaWs> data) {
    
    this.data = data;
    return this;
  }

  public EvidenciaWsPaginacio addDataItem(EvidenciaWs dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Elements retornats
   * @return data
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<EvidenciaWs> getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@javax.annotation.Nonnull List<EvidenciaWs> data) {
    this.data = data;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvidenciaWsPaginacio evidenciaWsPaginacio = (EvidenciaWsPaginacio) o;
    return Objects.equals(this.page, evidenciaWsPaginacio.page) &&
        Objects.equals(this.pagesize, evidenciaWsPaginacio.pagesize) &&
        Objects.equals(this.totalpages, evidenciaWsPaginacio.totalpages) &&
        Objects.equals(this.totalcount, evidenciaWsPaginacio.totalcount) &&
        Objects.equals(this.data, evidenciaWsPaginacio.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(page, pagesize, totalpages, totalcount, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvidenciaWsPaginacio {\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pagesize: ").append(toIndentedString(pagesize)).append("\n");
    sb.append("    totalpages: ").append(toIndentedString(totalpages)).append("\n");
    sb.append("    totalcount: ").append(toIndentedString(totalcount)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

