/*
 * API REST EXTERNA de EvidenciesIB - Evidencies
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.api.externa.client.evidencies.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.evidenciesib.api.externa.client.evidencies.v1.model.EvidenciaFile;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Estructura que inclou tota la informació de l&#39;evidència.
 */
@JsonPropertyOrder({
  EvidenciaWs.JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_R_R_O_R,
  EvidenciaWs.JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_C_R_E_A_C_I_O,
  EvidenciaWs.JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_L_O_G_I_N,
  EvidenciaWs.JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_F_I_R_M_A,
  EvidenciaWs.JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_S_I_G_N_A_T,
  EvidenciaWs.JSON_PROPERTY_EVIDENCIA_I_D,
  EvidenciaWs.JSON_PROPERTY_NOM,
  EvidenciaWs.JSON_PROPERTY_PERSONA_NOM,
  EvidenciaWs.JSON_PROPERTY_PERSONA_LLINATGE1,
  EvidenciaWs.JSON_PROPERTY_PERSONA_LLINATGE2,
  EvidenciaWs.JSON_PROPERTY_PERSONA_NIF,
  EvidenciaWs.JSON_PROPERTY_PERSONA_EMAIL,
  EvidenciaWs.JSON_PROPERTY_PERSONA_MOBIL,
  EvidenciaWs.JSON_PROPERTY_DATA_INICI,
  EvidenciaWs.JSON_PROPERTY_DATA_FI,
  EvidenciaWs.JSON_PROPERTY_ESTAT_CODI,
  EvidenciaWs.JSON_PROPERTY_ESTAT_CODI_DESCRIPCIO,
  EvidenciaWs.JSON_PROPERTY_ESTAT_ERROR,
  EvidenciaWs.JSON_PROPERTY_ESTAT_EXCEPCIO,
  EvidenciaWs.JSON_PROPERTY_LOGIN_TYPE,
  EvidenciaWs.JSON_PROPERTY_LOGIN_SUBTYPE,
  EvidenciaWs.JSON_PROPERTY_LOGIN_QAA,
  EvidenciaWs.JSON_PROPERTY_LOGIN_DATA,
  EvidenciaWs.JSON_PROPERTY_LOGIN_ID,
  EvidenciaWs.JSON_PROPERTY_LOGIN_AUTH_METHOD,
  EvidenciaWs.JSON_PROPERTY_LOGIN_ADDITIONAL_PROPERTIES,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_IP,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_CODI_POSTAL,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_LATITUD,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_LONGITUD,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_CIUTAT,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_REGIO,
  EvidenciaWs.JSON_PROPERTY_LOCALITZACIO_PAIS,
  EvidenciaWs.JSON_PROPERTY_FIRMA_REASON,
  EvidenciaWs.JSON_PROPERTY_FIRMA_IDIOMA_DOCUMENT,
  EvidenciaWs.JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL,
  EvidenciaWs.JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL_DESCRIPCIO,
  EvidenciaWs.JSON_PROPERTY_FITXER_ORIGINAL,
  EvidenciaWs.JSON_PROPERTY_FITXER_ADAPTAT,
  EvidenciaWs.JSON_PROPERTY_FITXER_SIGNAT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class EvidenciaWs {
  public static final String JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_R_R_O_R = "EVIDENCIA_ESTAT_CODI_ERROR";
  @javax.annotation.Nonnull
  private Integer EVIDENCIA_ESTAT_CODI_ERROR = -1;

  public static final String JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_C_R_E_A_C_I_O = "EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO";
  @javax.annotation.Nonnull
  private Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO = 1;

  public static final String JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_L_O_G_I_N = "EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN";
  @javax.annotation.Nonnull
  private Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN = 2;

  public static final String JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_F_I_R_M_A = "EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA";
  @javax.annotation.Nonnull
  private Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA = 3;

  public static final String JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_S_I_G_N_A_T = "EVIDENCIA_ESTAT_CODI_SIGNAT";
  @javax.annotation.Nonnull
  private Integer EVIDENCIA_ESTAT_CODI_SIGNAT = 10;

  public static final String JSON_PROPERTY_EVIDENCIA_I_D = "evidenciaID";
  @javax.annotation.Nullable
  private Long evidenciaID;

  public static final String JSON_PROPERTY_NOM = "nom";
  @javax.annotation.Nullable
  private String nom;

  public static final String JSON_PROPERTY_PERSONA_NOM = "personaNom";
  @javax.annotation.Nonnull
  private String personaNom;

  public static final String JSON_PROPERTY_PERSONA_LLINATGE1 = "personaLlinatge1";
  @javax.annotation.Nonnull
  private String personaLlinatge1;

  public static final String JSON_PROPERTY_PERSONA_LLINATGE2 = "personaLlinatge2";
  @javax.annotation.Nonnull
  private String personaLlinatge2;

  public static final String JSON_PROPERTY_PERSONA_NIF = "personaNif";
  @javax.annotation.Nonnull
  private String personaNif;

  public static final String JSON_PROPERTY_PERSONA_EMAIL = "personaEmail";
  @javax.annotation.Nullable
  private String personaEmail;

  public static final String JSON_PROPERTY_PERSONA_MOBIL = "personaMobil";
  @javax.annotation.Nullable
  private String personaMobil;

  public static final String JSON_PROPERTY_DATA_INICI = "dataInici";
  @javax.annotation.Nonnull
  private OffsetDateTime dataInici;

  public static final String JSON_PROPERTY_DATA_FI = "dataFi";
  @javax.annotation.Nullable
  private OffsetDateTime dataFi;

  public static final String JSON_PROPERTY_ESTAT_CODI = "estatCodi";
  @javax.annotation.Nullable
  private Integer estatCodi;

  public static final String JSON_PROPERTY_ESTAT_CODI_DESCRIPCIO = "estatCodiDescripcio";
  @javax.annotation.Nullable
  private String estatCodiDescripcio;

  public static final String JSON_PROPERTY_ESTAT_ERROR = "estatError";
  @javax.annotation.Nullable
  private String estatError;

  public static final String JSON_PROPERTY_ESTAT_EXCEPCIO = "estatExcepcio";
  @javax.annotation.Nullable
  private String estatExcepcio;

  public static final String JSON_PROPERTY_LOGIN_TYPE = "loginType";
  @javax.annotation.Nonnull
  private String loginType;

  public static final String JSON_PROPERTY_LOGIN_SUBTYPE = "loginSubtype";
  @javax.annotation.Nonnull
  private String loginSubtype;

  public static final String JSON_PROPERTY_LOGIN_QAA = "loginQaa";
  @javax.annotation.Nonnull
  private String loginQaa;

  public static final String JSON_PROPERTY_LOGIN_DATA = "loginData";
  @javax.annotation.Nonnull
  private OffsetDateTime loginData;

  public static final String JSON_PROPERTY_LOGIN_ID = "loginId";
  @javax.annotation.Nonnull
  private String loginId;

  public static final String JSON_PROPERTY_LOGIN_AUTH_METHOD = "loginAuthMethod";
  @javax.annotation.Nullable
  private String loginAuthMethod;

  public static final String JSON_PROPERTY_LOGIN_ADDITIONAL_PROPERTIES = "loginAdditionalProperties";
  @javax.annotation.Nullable
  private String loginAdditionalProperties;

  public static final String JSON_PROPERTY_LOCALITZACIO_IP = "localitzacioIp";
  @javax.annotation.Nullable
  private String localitzacioIp;

  public static final String JSON_PROPERTY_LOCALITZACIO_CODI_POSTAL = "localitzacioCodiPostal";
  @javax.annotation.Nullable
  private String localitzacioCodiPostal;

  public static final String JSON_PROPERTY_LOCALITZACIO_LATITUD = "localitzacioLatitud";
  @javax.annotation.Nullable
  private String localitzacioLatitud;

  public static final String JSON_PROPERTY_LOCALITZACIO_LONGITUD = "localitzacioLongitud";
  @javax.annotation.Nullable
  private String localitzacioLongitud;

  public static final String JSON_PROPERTY_LOCALITZACIO_CIUTAT = "localitzacioCiutat";
  @javax.annotation.Nullable
  private String localitzacioCiutat;

  public static final String JSON_PROPERTY_LOCALITZACIO_REGIO = "localitzacioRegio";
  @javax.annotation.Nullable
  private String localitzacioRegio;

  public static final String JSON_PROPERTY_LOCALITZACIO_PAIS = "localitzacioPais";
  @javax.annotation.Nullable
  private String localitzacioPais;

  public static final String JSON_PROPERTY_FIRMA_REASON = "firmaReason";
  @javax.annotation.Nonnull
  private String firmaReason;

  public static final String JSON_PROPERTY_FIRMA_IDIOMA_DOCUMENT = "firmaIdiomaDocument";
  @javax.annotation.Nonnull
  private String firmaIdiomaDocument;

  public static final String JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL = "firmaTipusDocumental";
  @javax.annotation.Nonnull
  private Integer firmaTipusDocumental;

  public static final String JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL_DESCRIPCIO = "firmaTipusDocumentalDescripcio";
  @javax.annotation.Nonnull
  private String firmaTipusDocumentalDescripcio;

  public static final String JSON_PROPERTY_FITXER_ORIGINAL = "fitxerOriginal";
  @javax.annotation.Nonnull
  private EvidenciaFile fitxerOriginal;

  public static final String JSON_PROPERTY_FITXER_ADAPTAT = "fitxerAdaptat";
  @javax.annotation.Nullable
  private EvidenciaFile fitxerAdaptat;

  public static final String JSON_PROPERTY_FITXER_SIGNAT = "fitxerSignat";
  @javax.annotation.Nullable
  private EvidenciaFile fitxerSignat;

  public EvidenciaWs() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public EvidenciaWs(
    @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_R_R_O_R) Integer EVIDENCIA_ESTAT_CODI_ERROR, 
    @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_C_R_E_A_C_I_O) Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO, 
    @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_L_O_G_I_N) Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN, 
    @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_F_I_R_M_A) Integer EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA, 
    @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_S_I_G_N_A_T) Integer EVIDENCIA_ESTAT_CODI_SIGNAT
  ) {
    this();
    this.EVIDENCIA_ESTAT_CODI_ERROR = EVIDENCIA_ESTAT_CODI_ERROR;
    this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO = EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO;
    this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN = EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN;
    this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA = EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA;
    this.EVIDENCIA_ESTAT_CODI_SIGNAT = EVIDENCIA_ESTAT_CODI_SIGNAT;
  }

  /**
   * Codi d&#39;estat d&#39;una evidència que indica un error
   * @return EVIDENCIA_ESTAT_CODI_ERROR
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_R_R_O_R)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEVIDENCIAESTATCODIERROR() {
    return EVIDENCIA_ESTAT_CODI_ERROR;
  }



  /**
   * Codi d&#39;estat d&#39;una evidència que indica que esta en procés de creació
   * @return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_C_R_E_A_C_I_O)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEVIDENCIAESTATCODIENPROCESDECREACIO() {
    return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO;
  }



  /**
   * Codi d&#39;estat d&#39;una evidència que indica que esta realitzant el login
   * @return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_L_O_G_I_N)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEVIDENCIAESTATCODIENPROCESDELOGIN() {
    return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN;
  }



  /**
   * Codi d&#39;estat d&#39;una evidència que indica que esta realitzant la firma del document
   * @return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_E_N_P_R_O_C_E_S_D_E_F_I_R_M_A)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEVIDENCIAESTATCODIENPROCESDEFIRMA() {
    return EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA;
  }



  /**
   * Codi d&#39;estat d&#39;una evidència que indica que ha finalitzat correctament
   * @return EVIDENCIA_ESTAT_CODI_SIGNAT
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_E_V_I_D_E_N_C_I_A_E_S_T_A_T_C_O_D_I_S_I_G_N_A_T)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEVIDENCIAESTATCODISIGNAT() {
    return EVIDENCIA_ESTAT_CODI_SIGNAT;
  }



  public EvidenciaWs evidenciaID(@javax.annotation.Nullable Long evidenciaID) {
    
    this.evidenciaID = evidenciaID;
    return this;
  }

  /**
   * Identificador únic de l&#39;evidència.
   * @return evidenciaID
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVIDENCIA_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEvidenciaID() {
    return evidenciaID;
  }


  @JsonProperty(JSON_PROPERTY_EVIDENCIA_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvidenciaID(@javax.annotation.Nullable Long evidenciaID) {
    this.evidenciaID = evidenciaID;
  }

  public EvidenciaWs nom(@javax.annotation.Nullable String nom) {
    
    this.nom = nom;
    return this;
  }

  /**
   * Nom descriptiu de l&#39;evidència.
   * @return nom
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(@javax.annotation.Nullable String nom) {
    this.nom = nom;
  }

  public EvidenciaWs personaNom(@javax.annotation.Nonnull String personaNom) {
    
    this.personaNom = personaNom;
    return this;
  }

  /**
   * Nom de la persona
   * @return personaNom
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERSONA_NOM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPersonaNom() {
    return personaNom;
  }


  @JsonProperty(JSON_PROPERTY_PERSONA_NOM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonaNom(@javax.annotation.Nonnull String personaNom) {
    this.personaNom = personaNom;
  }

  public EvidenciaWs personaLlinatge1(@javax.annotation.Nonnull String personaLlinatge1) {
    
    this.personaLlinatge1 = personaLlinatge1;
    return this;
  }

  /**
   * Primer llinatge de la persona
   * @return personaLlinatge1
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERSONA_LLINATGE1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPersonaLlinatge1() {
    return personaLlinatge1;
  }


  @JsonProperty(JSON_PROPERTY_PERSONA_LLINATGE1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonaLlinatge1(@javax.annotation.Nonnull String personaLlinatge1) {
    this.personaLlinatge1 = personaLlinatge1;
  }

  public EvidenciaWs personaLlinatge2(@javax.annotation.Nonnull String personaLlinatge2) {
    
    this.personaLlinatge2 = personaLlinatge2;
    return this;
  }

  /**
   * Segon llintge de la persona
   * @return personaLlinatge2
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERSONA_LLINATGE2)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPersonaLlinatge2() {
    return personaLlinatge2;
  }


  @JsonProperty(JSON_PROPERTY_PERSONA_LLINATGE2)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonaLlinatge2(@javax.annotation.Nonnull String personaLlinatge2) {
    this.personaLlinatge2 = personaLlinatge2;
  }

  public EvidenciaWs personaNif(@javax.annotation.Nonnull String personaNif) {
    
    this.personaNif = personaNif;
    return this;
  }

  /**
   * Nif de la persona
   * @return personaNif
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERSONA_NIF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPersonaNif() {
    return personaNif;
  }


  @JsonProperty(JSON_PROPERTY_PERSONA_NIF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonaNif(@javax.annotation.Nonnull String personaNif) {
    this.personaNif = personaNif;
  }

  public EvidenciaWs personaEmail(@javax.annotation.Nullable String personaEmail) {
    
    this.personaEmail = personaEmail;
    return this;
  }

  /**
   * Email de la persona
   * @return personaEmail
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERSONA_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPersonaEmail() {
    return personaEmail;
  }


  @JsonProperty(JSON_PROPERTY_PERSONA_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPersonaEmail(@javax.annotation.Nullable String personaEmail) {
    this.personaEmail = personaEmail;
  }

  public EvidenciaWs personaMobil(@javax.annotation.Nullable String personaMobil) {
    
    this.personaMobil = personaMobil;
    return this;
  }

  /**
   * Mòbil de la persona
   * @return personaMobil
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERSONA_MOBIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPersonaMobil() {
    return personaMobil;
  }


  @JsonProperty(JSON_PROPERTY_PERSONA_MOBIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPersonaMobil(@javax.annotation.Nullable String personaMobil) {
    this.personaMobil = personaMobil;
  }

  public EvidenciaWs dataInici(@javax.annotation.Nonnull OffsetDateTime dataInici) {
    
    this.dataInici = dataInici;
    return this;
  }

  /**
   * Data de creació de l&#39;evidència
   * @return dataInici
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATA_INICI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getDataInici() {
    return dataInici;
  }


  @JsonProperty(JSON_PROPERTY_DATA_INICI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDataInici(@javax.annotation.Nonnull OffsetDateTime dataInici) {
    this.dataInici = dataInici;
  }

  public EvidenciaWs dataFi(@javax.annotation.Nullable OffsetDateTime dataFi) {
    
    this.dataFi = dataFi;
    return this;
  }

  /**
   * Data final de l&#39;evidència
   * @return dataFi
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_FI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDataFi() {
    return dataFi;
  }


  @JsonProperty(JSON_PROPERTY_DATA_FI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataFi(@javax.annotation.Nullable OffsetDateTime dataFi) {
    this.dataFi = dataFi;
  }

  public EvidenciaWs estatCodi(@javax.annotation.Nullable Integer estatCodi) {
    
    this.estatCodi = estatCodi;
    return this;
  }

  /**
   * Estat en que ha finalitzat l&#39;evidència. Posibles estats:      public static final int EVIDENCIA_ESTAT_CODI_ERROR &#x3D; -1;      public static final int EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO &#x3D; 1;      public static final int EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN &#x3D; 2;      public static final int EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA &#x3D; 3;      public static final int EVIDENCIA_ESTAT_CODI_SIGNAT &#x3D; 10;
   * @return estatCodi
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT_CODI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEstatCodi() {
    return estatCodi;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT_CODI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstatCodi(@javax.annotation.Nullable Integer estatCodi) {
    this.estatCodi = estatCodi;
  }

  public EvidenciaWs estatCodiDescripcio(@javax.annotation.Nullable String estatCodiDescripcio) {
    
    this.estatCodiDescripcio = estatCodiDescripcio;
    return this;
  }

  /**
   * Descripció del camp estatCodi
   * @return estatCodiDescripcio
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT_CODI_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEstatCodiDescripcio() {
    return estatCodiDescripcio;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT_CODI_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstatCodiDescripcio(@javax.annotation.Nullable String estatCodiDescripcio) {
    this.estatCodiDescripcio = estatCodiDescripcio;
  }

  public EvidenciaWs estatError(@javax.annotation.Nullable String estatError) {
    
    this.estatError = estatError;
    return this;
  }

  /**
   * Missatge de l&#39;error
   * @return estatError
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEstatError() {
    return estatError;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstatError(@javax.annotation.Nullable String estatError) {
    this.estatError = estatError;
  }

  public EvidenciaWs estatExcepcio(@javax.annotation.Nullable String estatExcepcio) {
    
    this.estatExcepcio = estatExcepcio;
    return this;
  }

  /**
   * Stacktrace de l&#39;excepció si n&#39;hi hagues
   * @return estatExcepcio
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT_EXCEPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEstatExcepcio() {
    return estatExcepcio;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT_EXCEPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstatExcepcio(@javax.annotation.Nullable String estatExcepcio) {
    this.estatExcepcio = estatExcepcio;
  }

  public EvidenciaWs loginType(@javax.annotation.Nonnull String loginType) {
    
    this.loginType = loginType;
    return this;
  }

  /**
   * Tipus de Login
   * @return loginType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGIN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoginType() {
    return loginType;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoginType(@javax.annotation.Nonnull String loginType) {
    this.loginType = loginType;
  }

  public EvidenciaWs loginSubtype(@javax.annotation.Nonnull String loginSubtype) {
    
    this.loginSubtype = loginSubtype;
    return this;
  }

  /**
   * Subtipus de login
   * @return loginSubtype
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGIN_SUBTYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoginSubtype() {
    return loginSubtype;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_SUBTYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoginSubtype(@javax.annotation.Nonnull String loginSubtype) {
    this.loginSubtype = loginSubtype;
  }

  public EvidenciaWs loginQaa(@javax.annotation.Nonnull String loginQaa) {
    
    this.loginQaa = loginQaa;
    return this;
  }

  /**
   * Nivell des eguretat de login
   * @return loginQaa
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGIN_QAA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoginQaa() {
    return loginQaa;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_QAA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoginQaa(@javax.annotation.Nonnull String loginQaa) {
    this.loginQaa = loginQaa;
  }

  public EvidenciaWs loginData(@javax.annotation.Nonnull OffsetDateTime loginData) {
    
    this.loginData = loginData;
    return this;
  }

  /**
   * Data de realització del login
   * @return loginData
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGIN_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getLoginData() {
    return loginData;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoginData(@javax.annotation.Nonnull OffsetDateTime loginData) {
    this.loginData = loginData;
  }

  public EvidenciaWs loginId(@javax.annotation.Nonnull String loginId) {
    
    this.loginId = loginId;
    return this;
  }

  /**
   * Identificador del login realitzat.
   * @return loginId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGIN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoginId() {
    return loginId;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoginId(@javax.annotation.Nonnull String loginId) {
    this.loginId = loginId;
  }

  public EvidenciaWs loginAuthMethod(@javax.annotation.Nullable String loginAuthMethod) {
    
    this.loginAuthMethod = loginAuthMethod;
    return this;
  }

  /**
   * Get loginAuthMethod
   * @return loginAuthMethod
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGIN_AUTH_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoginAuthMethod() {
    return loginAuthMethod;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_AUTH_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoginAuthMethod(@javax.annotation.Nullable String loginAuthMethod) {
    this.loginAuthMethod = loginAuthMethod;
  }

  public EvidenciaWs loginAdditionalProperties(@javax.annotation.Nullable String loginAdditionalProperties) {
    
    this.loginAdditionalProperties = loginAdditionalProperties;
    return this;
  }

  /**
   * Get loginAdditionalProperties
   * @return loginAdditionalProperties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGIN_ADDITIONAL_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoginAdditionalProperties() {
    return loginAdditionalProperties;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_ADDITIONAL_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoginAdditionalProperties(@javax.annotation.Nullable String loginAdditionalProperties) {
    this.loginAdditionalProperties = loginAdditionalProperties;
  }

  public EvidenciaWs localitzacioIp(@javax.annotation.Nullable String localitzacioIp) {
    
    this.localitzacioIp = localitzacioIp;
    return this;
  }

  /**
   * IP des d&#39;on està connectat el ciutadà
   * @return localitzacioIp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioIp() {
    return localitzacioIp;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioIp(@javax.annotation.Nullable String localitzacioIp) {
    this.localitzacioIp = localitzacioIp;
  }

  public EvidenciaWs localitzacioCodiPostal(@javax.annotation.Nullable String localitzacioCodiPostal) {
    
    this.localitzacioCodiPostal = localitzacioCodiPostal;
    return this;
  }

  /**
   * Codi postal des d&#39;on està connectat el ciutadà.
   * @return localitzacioCodiPostal
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_CODI_POSTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioCodiPostal() {
    return localitzacioCodiPostal;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_CODI_POSTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioCodiPostal(@javax.annotation.Nullable String localitzacioCodiPostal) {
    this.localitzacioCodiPostal = localitzacioCodiPostal;
  }

  public EvidenciaWs localitzacioLatitud(@javax.annotation.Nullable String localitzacioLatitud) {
    
    this.localitzacioLatitud = localitzacioLatitud;
    return this;
  }

  /**
   * Latitud des d&#39;on està connectat el ciutadà.
   * @return localitzacioLatitud
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_LATITUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioLatitud() {
    return localitzacioLatitud;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_LATITUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioLatitud(@javax.annotation.Nullable String localitzacioLatitud) {
    this.localitzacioLatitud = localitzacioLatitud;
  }

  public EvidenciaWs localitzacioLongitud(@javax.annotation.Nullable String localitzacioLongitud) {
    
    this.localitzacioLongitud = localitzacioLongitud;
    return this;
  }

  /**
   * Longitud des d&#39;on està connectat el ciutadà.
   * @return localitzacioLongitud
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_LONGITUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioLongitud() {
    return localitzacioLongitud;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_LONGITUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioLongitud(@javax.annotation.Nullable String localitzacioLongitud) {
    this.localitzacioLongitud = localitzacioLongitud;
  }

  public EvidenciaWs localitzacioCiutat(@javax.annotation.Nullable String localitzacioCiutat) {
    
    this.localitzacioCiutat = localitzacioCiutat;
    return this;
  }

  /**
   * Localitat des d&#39;on està connectat el ciutadà.
   * @return localitzacioCiutat
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_CIUTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioCiutat() {
    return localitzacioCiutat;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_CIUTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioCiutat(@javax.annotation.Nullable String localitzacioCiutat) {
    this.localitzacioCiutat = localitzacioCiutat;
  }

  public EvidenciaWs localitzacioRegio(@javax.annotation.Nullable String localitzacioRegio) {
    
    this.localitzacioRegio = localitzacioRegio;
    return this;
  }

  /**
   * Regió (Si és Espanya Comunitat Autonoma) des d&#39;on està connectat el ciutadà.
   * @return localitzacioRegio
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_REGIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioRegio() {
    return localitzacioRegio;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_REGIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioRegio(@javax.annotation.Nullable String localitzacioRegio) {
    this.localitzacioRegio = localitzacioRegio;
  }

  public EvidenciaWs localitzacioPais(@javax.annotation.Nullable String localitzacioPais) {
    
    this.localitzacioPais = localitzacioPais;
    return this;
  }

  /**
   * Pais des d&#39;on està connectat el ciutadà.
   * @return localitzacioPais
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_PAIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalitzacioPais() {
    return localitzacioPais;
  }


  @JsonProperty(JSON_PROPERTY_LOCALITZACIO_PAIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalitzacioPais(@javax.annotation.Nullable String localitzacioPais) {
    this.localitzacioPais = localitzacioPais;
  }

  public EvidenciaWs firmaReason(@javax.annotation.Nonnull String firmaReason) {
    
    this.firmaReason = firmaReason;
    return this;
  }

  /**
   * Raó de firma.
   * @return firmaReason
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRMA_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirmaReason() {
    return firmaReason;
  }


  @JsonProperty(JSON_PROPERTY_FIRMA_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirmaReason(@javax.annotation.Nonnull String firmaReason) {
    this.firmaReason = firmaReason;
  }

  public EvidenciaWs firmaIdiomaDocument(@javax.annotation.Nonnull String firmaIdiomaDocument) {
    
    this.firmaIdiomaDocument = firmaIdiomaDocument;
    return this;
  }

  /**
   * Idioma en que està escrit el document.
   * @return firmaIdiomaDocument
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRMA_IDIOMA_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirmaIdiomaDocument() {
    return firmaIdiomaDocument;
  }


  @JsonProperty(JSON_PROPERTY_FIRMA_IDIOMA_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirmaIdiomaDocument(@javax.annotation.Nonnull String firmaIdiomaDocument) {
    this.firmaIdiomaDocument = firmaIdiomaDocument;
  }

  public EvidenciaWs firmaTipusDocumental(@javax.annotation.Nonnull Integer firmaTipusDocumental) {
    
    this.firmaTipusDocumental = firmaTipusDocumental;
    return this;
  }

  /**
   * Tipus documental de la Firma. Veure https://administracionelectronica.gob.es/pae_Home/dam/jcr:26d90313-7af0-4f69-9d62-c853d55d7627/Esquema_Metadatos_e-EMGDE_2016.pdf
   * @return firmaTipusDocumental
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getFirmaTipusDocumental() {
    return firmaTipusDocumental;
  }


  @JsonProperty(JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirmaTipusDocumental(@javax.annotation.Nonnull Integer firmaTipusDocumental) {
    this.firmaTipusDocumental = firmaTipusDocumental;
  }

  public EvidenciaWs firmaTipusDocumentalDescripcio(@javax.annotation.Nonnull String firmaTipusDocumentalDescripcio) {
    
    this.firmaTipusDocumentalDescripcio = firmaTipusDocumentalDescripcio;
    return this;
  }

  /**
   * DescripcioTipus documental de la Firma.Per exemple per 1 retorna &#39;Resolución(TD01)&#39;
   * @return firmaTipusDocumentalDescripcio
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirmaTipusDocumentalDescripcio() {
    return firmaTipusDocumentalDescripcio;
  }


  @JsonProperty(JSON_PROPERTY_FIRMA_TIPUS_DOCUMENTAL_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirmaTipusDocumentalDescripcio(@javax.annotation.Nonnull String firmaTipusDocumentalDescripcio) {
    this.firmaTipusDocumentalDescripcio = firmaTipusDocumentalDescripcio;
  }

  public EvidenciaWs fitxerOriginal(@javax.annotation.Nonnull EvidenciaFile fitxerOriginal) {
    
    this.fitxerOriginal = fitxerOriginal;
    return this;
  }

  /**
   * Get fitxerOriginal
   * @return fitxerOriginal
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FITXER_ORIGINAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EvidenciaFile getFitxerOriginal() {
    return fitxerOriginal;
  }


  @JsonProperty(JSON_PROPERTY_FITXER_ORIGINAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFitxerOriginal(@javax.annotation.Nonnull EvidenciaFile fitxerOriginal) {
    this.fitxerOriginal = fitxerOriginal;
  }

  public EvidenciaWs fitxerAdaptat(@javax.annotation.Nullable EvidenciaFile fitxerAdaptat) {
    
    this.fitxerAdaptat = fitxerAdaptat;
    return this;
  }

  /**
   * Get fitxerAdaptat
   * @return fitxerAdaptat
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FITXER_ADAPTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EvidenciaFile getFitxerAdaptat() {
    return fitxerAdaptat;
  }


  @JsonProperty(JSON_PROPERTY_FITXER_ADAPTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFitxerAdaptat(@javax.annotation.Nullable EvidenciaFile fitxerAdaptat) {
    this.fitxerAdaptat = fitxerAdaptat;
  }

  public EvidenciaWs fitxerSignat(@javax.annotation.Nullable EvidenciaFile fitxerSignat) {
    
    this.fitxerSignat = fitxerSignat;
    return this;
  }

  /**
   * Get fitxerSignat
   * @return fitxerSignat
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FITXER_SIGNAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EvidenciaFile getFitxerSignat() {
    return fitxerSignat;
  }


  @JsonProperty(JSON_PROPERTY_FITXER_SIGNAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFitxerSignat(@javax.annotation.Nullable EvidenciaFile fitxerSignat) {
    this.fitxerSignat = fitxerSignat;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvidenciaWs evidenciaWs = (EvidenciaWs) o;
    return Objects.equals(this.EVIDENCIA_ESTAT_CODI_ERROR, evidenciaWs.EVIDENCIA_ESTAT_CODI_ERROR) &&
        Objects.equals(this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO, evidenciaWs.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO) &&
        Objects.equals(this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN, evidenciaWs.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN) &&
        Objects.equals(this.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA, evidenciaWs.EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA) &&
        Objects.equals(this.EVIDENCIA_ESTAT_CODI_SIGNAT, evidenciaWs.EVIDENCIA_ESTAT_CODI_SIGNAT) &&
        Objects.equals(this.evidenciaID, evidenciaWs.evidenciaID) &&
        Objects.equals(this.nom, evidenciaWs.nom) &&
        Objects.equals(this.personaNom, evidenciaWs.personaNom) &&
        Objects.equals(this.personaLlinatge1, evidenciaWs.personaLlinatge1) &&
        Objects.equals(this.personaLlinatge2, evidenciaWs.personaLlinatge2) &&
        Objects.equals(this.personaNif, evidenciaWs.personaNif) &&
        Objects.equals(this.personaEmail, evidenciaWs.personaEmail) &&
        Objects.equals(this.personaMobil, evidenciaWs.personaMobil) &&
        Objects.equals(this.dataInici, evidenciaWs.dataInici) &&
        Objects.equals(this.dataFi, evidenciaWs.dataFi) &&
        Objects.equals(this.estatCodi, evidenciaWs.estatCodi) &&
        Objects.equals(this.estatCodiDescripcio, evidenciaWs.estatCodiDescripcio) &&
        Objects.equals(this.estatError, evidenciaWs.estatError) &&
        Objects.equals(this.estatExcepcio, evidenciaWs.estatExcepcio) &&
        Objects.equals(this.loginType, evidenciaWs.loginType) &&
        Objects.equals(this.loginSubtype, evidenciaWs.loginSubtype) &&
        Objects.equals(this.loginQaa, evidenciaWs.loginQaa) &&
        Objects.equals(this.loginData, evidenciaWs.loginData) &&
        Objects.equals(this.loginId, evidenciaWs.loginId) &&
        Objects.equals(this.loginAuthMethod, evidenciaWs.loginAuthMethod) &&
        Objects.equals(this.loginAdditionalProperties, evidenciaWs.loginAdditionalProperties) &&
        Objects.equals(this.localitzacioIp, evidenciaWs.localitzacioIp) &&
        Objects.equals(this.localitzacioCodiPostal, evidenciaWs.localitzacioCodiPostal) &&
        Objects.equals(this.localitzacioLatitud, evidenciaWs.localitzacioLatitud) &&
        Objects.equals(this.localitzacioLongitud, evidenciaWs.localitzacioLongitud) &&
        Objects.equals(this.localitzacioCiutat, evidenciaWs.localitzacioCiutat) &&
        Objects.equals(this.localitzacioRegio, evidenciaWs.localitzacioRegio) &&
        Objects.equals(this.localitzacioPais, evidenciaWs.localitzacioPais) &&
        Objects.equals(this.firmaReason, evidenciaWs.firmaReason) &&
        Objects.equals(this.firmaIdiomaDocument, evidenciaWs.firmaIdiomaDocument) &&
        Objects.equals(this.firmaTipusDocumental, evidenciaWs.firmaTipusDocumental) &&
        Objects.equals(this.firmaTipusDocumentalDescripcio, evidenciaWs.firmaTipusDocumentalDescripcio) &&
        Objects.equals(this.fitxerOriginal, evidenciaWs.fitxerOriginal) &&
        Objects.equals(this.fitxerAdaptat, evidenciaWs.fitxerAdaptat) &&
        Objects.equals(this.fitxerSignat, evidenciaWs.fitxerSignat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(EVIDENCIA_ESTAT_CODI_ERROR, EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO, EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN, EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA, EVIDENCIA_ESTAT_CODI_SIGNAT, evidenciaID, nom, personaNom, personaLlinatge1, personaLlinatge2, personaNif, personaEmail, personaMobil, dataInici, dataFi, estatCodi, estatCodiDescripcio, estatError, estatExcepcio, loginType, loginSubtype, loginQaa, loginData, loginId, loginAuthMethod, loginAdditionalProperties, localitzacioIp, localitzacioCodiPostal, localitzacioLatitud, localitzacioLongitud, localitzacioCiutat, localitzacioRegio, localitzacioPais, firmaReason, firmaIdiomaDocument, firmaTipusDocumental, firmaTipusDocumentalDescripcio, fitxerOriginal, fitxerAdaptat, fitxerSignat);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvidenciaWs {\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_ERROR: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_ERROR)).append("\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_CREACIO)).append("\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_LOGIN)).append("\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_EN_PROCES_DE_FIRMA)).append("\n");
    sb.append("    EVIDENCIA_ESTAT_CODI_SIGNAT: ").append(toIndentedString(EVIDENCIA_ESTAT_CODI_SIGNAT)).append("\n");
    sb.append("    evidenciaID: ").append(toIndentedString(evidenciaID)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    personaNom: ").append(toIndentedString(personaNom)).append("\n");
    sb.append("    personaLlinatge1: ").append(toIndentedString(personaLlinatge1)).append("\n");
    sb.append("    personaLlinatge2: ").append(toIndentedString(personaLlinatge2)).append("\n");
    sb.append("    personaNif: ").append(toIndentedString(personaNif)).append("\n");
    sb.append("    personaEmail: ").append(toIndentedString(personaEmail)).append("\n");
    sb.append("    personaMobil: ").append(toIndentedString(personaMobil)).append("\n");
    sb.append("    dataInici: ").append(toIndentedString(dataInici)).append("\n");
    sb.append("    dataFi: ").append(toIndentedString(dataFi)).append("\n");
    sb.append("    estatCodi: ").append(toIndentedString(estatCodi)).append("\n");
    sb.append("    estatCodiDescripcio: ").append(toIndentedString(estatCodiDescripcio)).append("\n");
    sb.append("    estatError: ").append(toIndentedString(estatError)).append("\n");
    sb.append("    estatExcepcio: ").append(toIndentedString(estatExcepcio)).append("\n");
    sb.append("    loginType: ").append(toIndentedString(loginType)).append("\n");
    sb.append("    loginSubtype: ").append(toIndentedString(loginSubtype)).append("\n");
    sb.append("    loginQaa: ").append(toIndentedString(loginQaa)).append("\n");
    sb.append("    loginData: ").append(toIndentedString(loginData)).append("\n");
    sb.append("    loginId: ").append(toIndentedString(loginId)).append("\n");
    sb.append("    loginAuthMethod: ").append(toIndentedString(loginAuthMethod)).append("\n");
    sb.append("    loginAdditionalProperties: ").append(toIndentedString(loginAdditionalProperties)).append("\n");
    sb.append("    localitzacioIp: ").append(toIndentedString(localitzacioIp)).append("\n");
    sb.append("    localitzacioCodiPostal: ").append(toIndentedString(localitzacioCodiPostal)).append("\n");
    sb.append("    localitzacioLatitud: ").append(toIndentedString(localitzacioLatitud)).append("\n");
    sb.append("    localitzacioLongitud: ").append(toIndentedString(localitzacioLongitud)).append("\n");
    sb.append("    localitzacioCiutat: ").append(toIndentedString(localitzacioCiutat)).append("\n");
    sb.append("    localitzacioRegio: ").append(toIndentedString(localitzacioRegio)).append("\n");
    sb.append("    localitzacioPais: ").append(toIndentedString(localitzacioPais)).append("\n");
    sb.append("    firmaReason: ").append(toIndentedString(firmaReason)).append("\n");
    sb.append("    firmaIdiomaDocument: ").append(toIndentedString(firmaIdiomaDocument)).append("\n");
    sb.append("    firmaTipusDocumental: ").append(toIndentedString(firmaTipusDocumental)).append("\n");
    sb.append("    firmaTipusDocumentalDescripcio: ").append(toIndentedString(firmaTipusDocumentalDescripcio)).append("\n");
    sb.append("    fitxerOriginal: ").append(toIndentedString(fitxerOriginal)).append("\n");
    sb.append("    fitxerAdaptat: ").append(toIndentedString(fitxerAdaptat)).append("\n");
    sb.append("    fitxerSignat: ").append(toIndentedString(fitxerSignat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

