/*
 * API REST EXTERNA de EvidenciesIB - Evidencies
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.api.externa.client.evidencies.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EvidenciaStartResponse
 */
@JsonPropertyOrder({
  EvidenciaStartResponse.JSON_PROPERTY_EVIDENCIA_I_D,
  EvidenciaStartResponse.JSON_PROPERTY_EVIDENCIA_URL_REDIRECT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EvidenciaStartResponse {
  public static final String JSON_PROPERTY_EVIDENCIA_I_D = "evidenciaID";
  private Long evidenciaID;

  public static final String JSON_PROPERTY_EVIDENCIA_URL_REDIRECT = "evidenciaUrlRedirect";
  private URI evidenciaUrlRedirect;

  public EvidenciaStartResponse() {
  }

  public EvidenciaStartResponse evidenciaID(Long evidenciaID) {
    
    this.evidenciaID = evidenciaID;
    return this;
  }

   /**
   * Identificador del nou procés de recolecció d&#39;evidències
   * @return evidenciaID
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EVIDENCIA_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getEvidenciaID() {
    return evidenciaID;
  }


  @JsonProperty(JSON_PROPERTY_EVIDENCIA_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEvidenciaID(Long evidenciaID) {
    this.evidenciaID = evidenciaID;
  }


  public EvidenciaStartResponse evidenciaUrlRedirect(URI evidenciaUrlRedirect) {
    
    this.evidenciaUrlRedirect = evidenciaUrlRedirect;
    return this;
  }

   /**
   * Adreça a on redirigir el navegador del client per iniciar la recolecció d&#39;evidències
   * @return evidenciaUrlRedirect
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EVIDENCIA_URL_REDIRECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public URI getEvidenciaUrlRedirect() {
    return evidenciaUrlRedirect;
  }


  @JsonProperty(JSON_PROPERTY_EVIDENCIA_URL_REDIRECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEvidenciaUrlRedirect(URI evidenciaUrlRedirect) {
    this.evidenciaUrlRedirect = evidenciaUrlRedirect;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvidenciaStartResponse evidenciaStartResponse = (EvidenciaStartResponse) o;
    return Objects.equals(this.evidenciaID, evidenciaStartResponse.evidenciaID) &&
        Objects.equals(this.evidenciaUrlRedirect, evidenciaStartResponse.evidenciaUrlRedirect);
  }

  @Override
  public int hashCode() {
    return Objects.hash(evidenciaID, evidenciaUrlRedirect);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvidenciaStartResponse {\n");
    sb.append("    evidenciaID: ").append(toIndentedString(evidenciaID)).append("\n");
    sb.append("    evidenciaUrlRedirect: ").append(toIndentedString(evidenciaUrlRedirect)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

