/*
 * API REST EXTERNA de EvidenciesIB - Evidencies
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.api.externa.client.evidencies.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Objecte per enviar i rebre fitxers així com la informació associada a aquest.
 */
@JsonPropertyOrder({
  EvidenciaFile.JSON_PROPERTY_NAME,
  EvidenciaFile.JSON_PROPERTY_MIME,
  EvidenciaFile.JSON_PROPERTY_SIZE,
  EvidenciaFile.JSON_PROPERTY_DESCRIPTION,
  EvidenciaFile.JSON_PROPERTY_ENCRYPTED_FILE_I_D,
  EvidenciaFile.JSON_PROPERTY_DOCUMENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EvidenciaFile {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_MIME = "mime";
  private String mime;

  public static final String JSON_PROPERTY_SIZE = "size";
  private Long size;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_ENCRYPTED_FILE_I_D = "encryptedFileID";
  private String encryptedFileID;

  public static final String JSON_PROPERTY_DOCUMENT = "document";
  private byte[] document;

  public EvidenciaFile() {
  }

  public EvidenciaFile name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Nom del fitxer
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public EvidenciaFile mime(String mime) {
    
    this.mime = mime;
    return this;
  }

   /**
   * Tipus MIME del Fitxer
   * @return mime
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMime() {
    return mime;
  }


  @JsonProperty(JSON_PROPERTY_MIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMime(String mime) {
    this.mime = mime;
  }


  public EvidenciaFile size(Long size) {
    
    this.size = size;
    return this;
  }

   /**
   * Mida en bytes del document
   * @return size
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSize() {
    return size;
  }


  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSize(Long size) {
    this.size = size;
  }


  public EvidenciaFile description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Descripció del Fitxer
   * @return description
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public EvidenciaFile encryptedFileID(String encryptedFileID) {
    
    this.encryptedFileID = encryptedFileID;
    return this;
  }

   /**
   * Identificar del fitxer per poder-ho recuperar en una segona fase. Només apareix en llistats per no incloure el contingut del fitxer.
   * @return encryptedFileID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENCRYPTED_FILE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEncryptedFileID() {
    return encryptedFileID;
  }


  @JsonProperty(JSON_PROPERTY_ENCRYPTED_FILE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncryptedFileID(String encryptedFileID) {
    this.encryptedFileID = encryptedFileID;
  }


  public EvidenciaFile document(byte[] document) {
    
    this.document = document;
    return this;
  }

   /**
   * Contingut del fitxer. En llistats aquest camp vendrà buit.
   * @return document
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getDocument() {
    return document;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocument(byte[] document) {
    this.document = document;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvidenciaFile evidenciaFile = (EvidenciaFile) o;
    return Objects.equals(this.name, evidenciaFile.name) &&
        Objects.equals(this.mime, evidenciaFile.mime) &&
        Objects.equals(this.size, evidenciaFile.size) &&
        Objects.equals(this.description, evidenciaFile.description) &&
        Objects.equals(this.encryptedFileID, evidenciaFile.encryptedFileID) &&
        Arrays.equals(this.document, evidenciaFile.document);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, mime, size, description, encryptedFileID, Arrays.hashCode(document));
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvidenciaFile {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mime: ").append(toIndentedString(mime)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    encryptedFileID: ").append(toIndentedString(encryptedFileID)).append("\n");
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

