/*
 * API REST EXTERNA de EvidenciesIB - Evidencies
 * Conjunt de Serveis REST de EvidenciesIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.evidenciesib.api.externa.client.evidencies.v1.api;

import es.caib.evidenciesib.api.externa.client.evidencies.v1.services.ApiException;
import es.caib.evidenciesib.api.externa.client.evidencies.v1.model.ConstantsWs;
import es.caib.evidenciesib.api.externa.client.evidencies.v1.model.EvidenciaFile;
import es.caib.evidenciesib.api.externa.client.evidencies.v1.model.EvidenciaFileBase64;
import es.caib.evidenciesib.api.externa.client.evidencies.v1.model.EvidenciaStartRequest;
import es.caib.evidenciesib.api.externa.client.evidencies.v1.model.EvidenciaStartResponse;
import es.caib.evidenciesib.api.externa.client.evidencies.v1.model.EvidenciaWs;
import es.caib.evidenciesib.api.externa.client.evidencies.v1.model.EvidenciaWsPaginacio;
import es.caib.evidenciesib.api.externa.client.evidencies.v1.model.RestExceptionInfo;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EvidenciesApi
 */
public class EvidenciesApiTest {

    private final EvidenciesApi api = new EvidenciesApi();

    /**
     * Retorna un llistat de les evidencies 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void callListTest() throws ApiException {
        //
        //String inici = null;
        //
        //String fi = null;
        //
        //Integer page = null;
        //
        //Integer pagesize = null;
        //
        //String language = null;
        //
        //EvidenciaWsPaginacio response = api.callList(inici, fi, page, pagesize, language);

        // TODO: test validations
    }
    /**
     * Retorna informació d&#39;una evidència a partir del seu id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTest() throws ApiException {
        //
        //Long evidenciaID = null;
        //
        //String language = null;
        //
        //EvidenciaWs response = api.get(evidenciaID, language);

        // TODO: test validations
    }
    /**
     * Retorna informació d&#39;un fitxer d&#39;una evidència a partir del encryptedFileID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getfileTest() throws ApiException {
        //
        //Long evidenciaID = null;
        //
        //String encryptedFileID = null;
        //
        //String language = null;
        //
        //EvidenciaFile response = api.getfile(evidenciaID, encryptedFileID, language);

        // TODO: test validations
    }
    /**
     * Retorna informació d&#39;un fitxer d&#39;una evidència a partir del encryptedFileID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getfilebase64Test() throws ApiException {
        //
        //Long evidenciaID = null;
        //
        //String encryptedFileID = null;
        //
        //String language = null;
        //
        //EvidenciaFileBase64 response = api.getfilebase64(evidenciaID, encryptedFileID, language);

        // TODO: test validations
    }
    /**
     * Primera cridada a realitzar per iniciar un procés d&#39;evidències
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void startTest() throws ApiException {
        //
        //EvidenciaStartRequest evidenciaStartRequest = null;
        //
        //EvidenciaStartResponse response = api.start(evidenciaStartRequest);

        // TODO: test validations
    }
    /**
     * Retorna la versió d&#39;aquest Servei
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versioTest() throws ApiException {
        //
        //String response = api.versio();

        // TODO: test validations
    }
}
